/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables.pojos;


import com.ke.bella.batch.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        batchId;
    private String        endpoint;
    private String        ak;
    private String        inputFileId;
    private String        completionWindow;
    private String        status;
    private String        outputFileId;
    private String        errorFileId;
    private LocalDateTime inProgressAt;
    private LocalDateTime expiredAt;
    private LocalDateTime finalizingAt;
    private LocalDateTime completedAt;
    private LocalDateTime failedAt;
    private LocalDateTime cancellingAt;
    private LocalDateTime cancelledAt;
    private Long          requestCountsTotal;
    private Long          requestCountsCompleted;
    private Long          requestCountsFailed;
    private Long          importCountsFailed;
    private String        matadata;
    private Long          cuid;
    private Long          muid;
    private String        cuName;
    private String        muName;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public BatchDB() {}

    public BatchDB(BatchDB value) {
        this.id = value.id;
        this.batchId = value.batchId;
        this.endpoint = value.endpoint;
        this.ak = value.ak;
        this.inputFileId = value.inputFileId;
        this.completionWindow = value.completionWindow;
        this.status = value.status;
        this.outputFileId = value.outputFileId;
        this.errorFileId = value.errorFileId;
        this.inProgressAt = value.inProgressAt;
        this.expiredAt = value.expiredAt;
        this.finalizingAt = value.finalizingAt;
        this.completedAt = value.completedAt;
        this.failedAt = value.failedAt;
        this.cancellingAt = value.cancellingAt;
        this.cancelledAt = value.cancelledAt;
        this.requestCountsTotal = value.requestCountsTotal;
        this.requestCountsCompleted = value.requestCountsCompleted;
        this.requestCountsFailed = value.requestCountsFailed;
        this.importCountsFailed = value.importCountsFailed;
        this.matadata = value.matadata;
        this.cuid = value.cuid;
        this.muid = value.muid;
        this.cuName = value.cuName;
        this.muName = value.muName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public BatchDB(
        Long          id,
        String        batchId,
        String        endpoint,
        String        ak,
        String        inputFileId,
        String        completionWindow,
        String        status,
        String        outputFileId,
        String        errorFileId,
        LocalDateTime inProgressAt,
        LocalDateTime expiredAt,
        LocalDateTime finalizingAt,
        LocalDateTime completedAt,
        LocalDateTime failedAt,
        LocalDateTime cancellingAt,
        LocalDateTime cancelledAt,
        Long          requestCountsTotal,
        Long          requestCountsCompleted,
        Long          requestCountsFailed,
        Long          importCountsFailed,
        String        matadata,
        Long          cuid,
        Long          muid,
        String        cuName,
        String        muName,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.batchId = batchId;
        this.endpoint = endpoint;
        this.ak = ak;
        this.inputFileId = inputFileId;
        this.completionWindow = completionWindow;
        this.status = status;
        this.outputFileId = outputFileId;
        this.errorFileId = errorFileId;
        this.inProgressAt = inProgressAt;
        this.expiredAt = expiredAt;
        this.finalizingAt = finalizingAt;
        this.completedAt = completedAt;
        this.failedAt = failedAt;
        this.cancellingAt = cancellingAt;
        this.cancelledAt = cancelledAt;
        this.requestCountsTotal = requestCountsTotal;
        this.requestCountsCompleted = requestCountsCompleted;
        this.requestCountsFailed = requestCountsFailed;
        this.importCountsFailed = importCountsFailed;
        this.matadata = matadata;
        this.cuid = cuid;
        this.muid = muid;
        this.cuName = cuName;
        this.muName = muName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>batch.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>batch.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>batch.batch_id</code>.
     */
    public String getBatchId() {
        return this.batchId;
    }

    /**
     * Setter for <code>batch.batch_id</code>.
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }

    /**
     * Getter for <code>batch.endpoint</code>.
     */
    public String getEndpoint() {
        return this.endpoint;
    }

    /**
     * Setter for <code>batch.endpoint</code>.
     */
    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    /**
     * Getter for <code>batch.ak</code>.
     */
    public String getAk() {
        return this.ak;
    }

    /**
     * Setter for <code>batch.ak</code>.
     */
    public void setAk(String ak) {
        this.ak = ak;
    }

    /**
     * Getter for <code>batch.input_file_id</code>.
     */
    public String getInputFileId() {
        return this.inputFileId;
    }

    /**
     * Setter for <code>batch.input_file_id</code>.
     */
    public void setInputFileId(String inputFileId) {
        this.inputFileId = inputFileId;
    }

    /**
     * Getter for <code>batch.completion_window</code>.
     */
    public String getCompletionWindow() {
        return this.completionWindow;
    }

    /**
     * Setter for <code>batch.completion_window</code>.
     */
    public void setCompletionWindow(String completionWindow) {
        this.completionWindow = completionWindow;
    }

    /**
     * Getter for <code>batch.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>batch.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>batch.output_file_id</code>.
     */
    public String getOutputFileId() {
        return this.outputFileId;
    }

    /**
     * Setter for <code>batch.output_file_id</code>.
     */
    public void setOutputFileId(String outputFileId) {
        this.outputFileId = outputFileId;
    }

    /**
     * Getter for <code>batch.error_file_id</code>.
     */
    public String getErrorFileId() {
        return this.errorFileId;
    }

    /**
     * Setter for <code>batch.error_file_id</code>.
     */
    public void setErrorFileId(String errorFileId) {
        this.errorFileId = errorFileId;
    }

    /**
     * Getter for <code>batch.in_progress_at</code>.
     */
    public LocalDateTime getInProgressAt() {
        return this.inProgressAt;
    }

    /**
     * Setter for <code>batch.in_progress_at</code>.
     */
    public void setInProgressAt(LocalDateTime inProgressAt) {
        this.inProgressAt = inProgressAt;
    }

    /**
     * Getter for <code>batch.expired_at</code>.
     */
    public LocalDateTime getExpiredAt() {
        return this.expiredAt;
    }

    /**
     * Setter for <code>batch.expired_at</code>.
     */
    public void setExpiredAt(LocalDateTime expiredAt) {
        this.expiredAt = expiredAt;
    }

    /**
     * Getter for <code>batch.finalizing_at</code>.
     */
    public LocalDateTime getFinalizingAt() {
        return this.finalizingAt;
    }

    /**
     * Setter for <code>batch.finalizing_at</code>.
     */
    public void setFinalizingAt(LocalDateTime finalizingAt) {
        this.finalizingAt = finalizingAt;
    }

    /**
     * Getter for <code>batch.completed_at</code>.
     */
    public LocalDateTime getCompletedAt() {
        return this.completedAt;
    }

    /**
     * Setter for <code>batch.completed_at</code>.
     */
    public void setCompletedAt(LocalDateTime completedAt) {
        this.completedAt = completedAt;
    }

    /**
     * Getter for <code>batch.failed_at</code>.
     */
    public LocalDateTime getFailedAt() {
        return this.failedAt;
    }

    /**
     * Setter for <code>batch.failed_at</code>.
     */
    public void setFailedAt(LocalDateTime failedAt) {
        this.failedAt = failedAt;
    }

    /**
     * Getter for <code>batch.cancelling_at</code>.
     */
    public LocalDateTime getCancellingAt() {
        return this.cancellingAt;
    }

    /**
     * Setter for <code>batch.cancelling_at</code>.
     */
    public void setCancellingAt(LocalDateTime cancellingAt) {
        this.cancellingAt = cancellingAt;
    }

    /**
     * Getter for <code>batch.cancelled_at</code>.
     */
    public LocalDateTime getCancelledAt() {
        return this.cancelledAt;
    }

    /**
     * Setter for <code>batch.cancelled_at</code>.
     */
    public void setCancelledAt(LocalDateTime cancelledAt) {
        this.cancelledAt = cancelledAt;
    }

    /**
     * Getter for <code>batch.request_counts_total</code>.
     */
    public Long getRequestCountsTotal() {
        return this.requestCountsTotal;
    }

    /**
     * Setter for <code>batch.request_counts_total</code>.
     */
    public void setRequestCountsTotal(Long requestCountsTotal) {
        this.requestCountsTotal = requestCountsTotal;
    }

    /**
     * Getter for <code>batch.request_counts_completed</code>.
     */
    public Long getRequestCountsCompleted() {
        return this.requestCountsCompleted;
    }

    /**
     * Setter for <code>batch.request_counts_completed</code>.
     */
    public void setRequestCountsCompleted(Long requestCountsCompleted) {
        this.requestCountsCompleted = requestCountsCompleted;
    }

    /**
     * Getter for <code>batch.request_counts_failed</code>.
     */
    public Long getRequestCountsFailed() {
        return this.requestCountsFailed;
    }

    /**
     * Setter for <code>batch.request_counts_failed</code>.
     */
    public void setRequestCountsFailed(Long requestCountsFailed) {
        this.requestCountsFailed = requestCountsFailed;
    }

    /**
     * Getter for <code>batch.import_counts_failed</code>.
     */
    public Long getImportCountsFailed() {
        return this.importCountsFailed;
    }

    /**
     * Setter for <code>batch.import_counts_failed</code>.
     */
    public void setImportCountsFailed(Long importCountsFailed) {
        this.importCountsFailed = importCountsFailed;
    }

    /**
     * Getter for <code>batch.matadata</code>.
     */
    public String getMatadata() {
        return this.matadata;
    }

    /**
     * Setter for <code>batch.matadata</code>.
     */
    public void setMatadata(String matadata) {
        this.matadata = matadata;
    }

    /**
     * Getter for <code>batch.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>batch.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>batch.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>batch.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>batch.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>batch.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>batch.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>batch.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>batch.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>batch.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>batch.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>batch.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BatchDB (");

        sb.append(id);
        sb.append(", ").append(batchId);
        sb.append(", ").append(endpoint);
        sb.append(", ").append(ak);
        sb.append(", ").append(inputFileId);
        sb.append(", ").append(completionWindow);
        sb.append(", ").append(status);
        sb.append(", ").append(outputFileId);
        sb.append(", ").append(errorFileId);
        sb.append(", ").append(inProgressAt);
        sb.append(", ").append(expiredAt);
        sb.append(", ").append(finalizingAt);
        sb.append(", ").append(completedAt);
        sb.append(", ").append(failedAt);
        sb.append(", ").append(cancellingAt);
        sb.append(", ").append(cancelledAt);
        sb.append(", ").append(requestCountsTotal);
        sb.append(", ").append(requestCountsCompleted);
        sb.append(", ").append(requestCountsFailed);
        sb.append(", ").append(importCountsFailed);
        sb.append(", ").append(matadata);
        sb.append(", ").append(cuid);
        sb.append(", ").append(muid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(muName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
