/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables.pojos;


import com.ke.bella.batch.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueueMetadataDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        queue;
    private String        endpoint;
    private Long          cuid;
    private Long          muid;
    private String        cuName;
    private String        muName;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public QueueMetadataDB() {}

    public QueueMetadataDB(QueueMetadataDB value) {
        this.id = value.id;
        this.queue = value.queue;
        this.endpoint = value.endpoint;
        this.cuid = value.cuid;
        this.muid = value.muid;
        this.cuName = value.cuName;
        this.muName = value.muName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public QueueMetadataDB(
        Long          id,
        String        queue,
        String        endpoint,
        Long          cuid,
        Long          muid,
        String        cuName,
        String        muName,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.queue = queue;
        this.endpoint = endpoint;
        this.cuid = cuid;
        this.muid = muid;
        this.cuName = cuName;
        this.muName = muName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>queue_metadata.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>queue_metadata.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>queue_metadata.queue</code>.
     */
    public String getQueue() {
        return this.queue;
    }

    /**
     * Setter for <code>queue_metadata.queue</code>.
     */
    public void setQueue(String queue) {
        this.queue = queue;
    }

    /**
     * Getter for <code>queue_metadata.endpoint</code>.
     */
    public String getEndpoint() {
        return this.endpoint;
    }

    /**
     * Setter for <code>queue_metadata.endpoint</code>.
     */
    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    /**
     * Getter for <code>queue_metadata.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>queue_metadata.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>queue_metadata.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>queue_metadata.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>queue_metadata.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>queue_metadata.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>queue_metadata.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>queue_metadata.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>queue_metadata.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>queue_metadata.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>queue_metadata.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>queue_metadata.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QueueMetadataDB (");

        sb.append(id);
        sb.append(", ").append(queue);
        sb.append(", ").append(endpoint);
        sb.append(", ").append(cuid);
        sb.append(", ").append(muid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(muName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
