/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables.pojos;


import com.ke.bella.batch.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueueDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        taskId;
    private String        customId;
    private String        queue;
    private String        endpoint;
    private String        ak;
    private String        batchId;
    private String        inputData;
    private String        inputFileId;
    private String        outputData;
    private String        outputFileId;
    private String        status;
    private String        callbackUrl;
    private LocalDateTime expiredAt;
    private String        traceId;
    private Long          cuid;
    private Long          muid;
    private String        cuName;
    private String        muName;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public QueueDB() {}

    public QueueDB(QueueDB value) {
        this.id = value.id;
        this.taskId = value.taskId;
        this.customId = value.customId;
        this.queue = value.queue;
        this.endpoint = value.endpoint;
        this.ak = value.ak;
        this.batchId = value.batchId;
        this.inputData = value.inputData;
        this.inputFileId = value.inputFileId;
        this.outputData = value.outputData;
        this.outputFileId = value.outputFileId;
        this.status = value.status;
        this.callbackUrl = value.callbackUrl;
        this.expiredAt = value.expiredAt;
        this.traceId = value.traceId;
        this.cuid = value.cuid;
        this.muid = value.muid;
        this.cuName = value.cuName;
        this.muName = value.muName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public QueueDB(
        Long          id,
        String        taskId,
        String        customId,
        String        queue,
        String        endpoint,
        String        ak,
        String        batchId,
        String        inputData,
        String        inputFileId,
        String        outputData,
        String        outputFileId,
        String        status,
        String        callbackUrl,
        LocalDateTime expiredAt,
        String        traceId,
        Long          cuid,
        Long          muid,
        String        cuName,
        String        muName,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.taskId = taskId;
        this.customId = customId;
        this.queue = queue;
        this.endpoint = endpoint;
        this.ak = ak;
        this.batchId = batchId;
        this.inputData = inputData;
        this.inputFileId = inputFileId;
        this.outputData = outputData;
        this.outputFileId = outputFileId;
        this.status = status;
        this.callbackUrl = callbackUrl;
        this.expiredAt = expiredAt;
        this.traceId = traceId;
        this.cuid = cuid;
        this.muid = muid;
        this.cuName = cuName;
        this.muName = muName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>queue.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>queue.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>queue.task_id</code>.
     */
    public String getTaskId() {
        return this.taskId;
    }

    /**
     * Setter for <code>queue.task_id</code>.
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * Getter for <code>queue.custom_id</code>.
     */
    public String getCustomId() {
        return this.customId;
    }

    /**
     * Setter for <code>queue.custom_id</code>.
     */
    public void setCustomId(String customId) {
        this.customId = customId;
    }

    /**
     * Getter for <code>queue.queue</code>.
     */
    public String getQueue() {
        return this.queue;
    }

    /**
     * Setter for <code>queue.queue</code>.
     */
    public void setQueue(String queue) {
        this.queue = queue;
    }

    /**
     * Getter for <code>queue.endpoint</code>.
     */
    public String getEndpoint() {
        return this.endpoint;
    }

    /**
     * Setter for <code>queue.endpoint</code>.
     */
    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    /**
     * Getter for <code>queue.ak</code>.
     */
    public String getAk() {
        return this.ak;
    }

    /**
     * Setter for <code>queue.ak</code>.
     */
    public void setAk(String ak) {
        this.ak = ak;
    }

    /**
     * Getter for <code>queue.batch_id</code>.
     */
    public String getBatchId() {
        return this.batchId;
    }

    /**
     * Setter for <code>queue.batch_id</code>.
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }

    /**
     * Getter for <code>queue.input_data</code>.
     */
    public String getInputData() {
        return this.inputData;
    }

    /**
     * Setter for <code>queue.input_data</code>.
     */
    public void setInputData(String inputData) {
        this.inputData = inputData;
    }

    /**
     * Getter for <code>queue.input_file_id</code>.
     */
    public String getInputFileId() {
        return this.inputFileId;
    }

    /**
     * Setter for <code>queue.input_file_id</code>.
     */
    public void setInputFileId(String inputFileId) {
        this.inputFileId = inputFileId;
    }

    /**
     * Getter for <code>queue.output_data</code>.
     */
    public String getOutputData() {
        return this.outputData;
    }

    /**
     * Setter for <code>queue.output_data</code>.
     */
    public void setOutputData(String outputData) {
        this.outputData = outputData;
    }

    /**
     * Getter for <code>queue.output_file_id</code>.
     */
    public String getOutputFileId() {
        return this.outputFileId;
    }

    /**
     * Setter for <code>queue.output_file_id</code>.
     */
    public void setOutputFileId(String outputFileId) {
        this.outputFileId = outputFileId;
    }

    /**
     * Getter for <code>queue.status</code>. waiting: 等待中, queued: 已入队, 
     * succeeded: 成功, timeout: 超时, cancelled: 已取消
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>queue.status</code>. waiting: 等待中, queued: 已入队, 
     * succeeded: 成功, timeout: 超时, cancelled: 已取消
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>queue.callback_url</code>.
     */
    public String getCallbackUrl() {
        return this.callbackUrl;
    }

    /**
     * Setter for <code>queue.callback_url</code>.
     */
    public void setCallbackUrl(String callbackUrl) {
        this.callbackUrl = callbackUrl;
    }

    /**
     * Getter for <code>queue.expired_at</code>.
     */
    public LocalDateTime getExpiredAt() {
        return this.expiredAt;
    }

    /**
     * Setter for <code>queue.expired_at</code>.
     */
    public void setExpiredAt(LocalDateTime expiredAt) {
        this.expiredAt = expiredAt;
    }

    /**
     * Getter for <code>queue.trace_id</code>.
     */
    public String getTraceId() {
        return this.traceId;
    }

    /**
     * Setter for <code>queue.trace_id</code>.
     */
    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    /**
     * Getter for <code>queue.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>queue.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>queue.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>queue.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>queue.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>queue.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>queue.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>queue.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>queue.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>queue.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>queue.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>queue.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QueueDB (");

        sb.append(id);
        sb.append(", ").append(taskId);
        sb.append(", ").append(customId);
        sb.append(", ").append(queue);
        sb.append(", ").append(endpoint);
        sb.append(", ").append(ak);
        sb.append(", ").append(batchId);
        sb.append(", ").append(inputData);
        sb.append(", ").append(inputFileId);
        sb.append(", ").append(outputData);
        sb.append(", ").append(outputFileId);
        sb.append(", ").append(status);
        sb.append(", ").append(callbackUrl);
        sb.append(", ").append(expiredAt);
        sb.append(", ").append(traceId);
        sb.append(", ").append(cuid);
        sb.append(", ").append(muid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(muName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
