/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables.pojos;


import com.ke.bella.batch.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueueShardingDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        key;
    private LocalDateTime keyTime;
    private String        queueTable;
    private String        lastKey;
    private Long          count;
    private Long          maxCount;
    private Long          cuid;
    private Long          muid;
    private String        cuName;
    private String        muName;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public QueueShardingDB() {}

    public QueueShardingDB(QueueShardingDB value) {
        this.id = value.id;
        this.key = value.key;
        this.keyTime = value.keyTime;
        this.queueTable = value.queueTable;
        this.lastKey = value.lastKey;
        this.count = value.count;
        this.maxCount = value.maxCount;
        this.cuid = value.cuid;
        this.muid = value.muid;
        this.cuName = value.cuName;
        this.muName = value.muName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public QueueShardingDB(
        Long          id,
        String        key,
        LocalDateTime keyTime,
        String        queueTable,
        String        lastKey,
        Long          count,
        Long          maxCount,
        Long          cuid,
        Long          muid,
        String        cuName,
        String        muName,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.key = key;
        this.keyTime = keyTime;
        this.queueTable = queueTable;
        this.lastKey = lastKey;
        this.count = count;
        this.maxCount = maxCount;
        this.cuid = cuid;
        this.muid = muid;
        this.cuName = cuName;
        this.muName = muName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>queue_sharding.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>queue_sharding.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>queue_sharding.key</code>. 分表的标识
     */
    public String getKey() {
        return this.key;
    }

    /**
     * Setter for <code>queue_sharding.key</code>. 分表的标识
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * Getter for <code>queue_sharding.key_time</code>.
     */
    public LocalDateTime getKeyTime() {
        return this.keyTime;
    }

    /**
     * Setter for <code>queue_sharding.key_time</code>.
     */
    public void setKeyTime(LocalDateTime keyTime) {
        this.keyTime = keyTime;
    }

    /**
     * Getter for <code>queue_sharding.queue_table</code>.
     */
    public String getQueueTable() {
        return this.queueTable;
    }

    /**
     * Setter for <code>queue_sharding.queue_table</code>.
     */
    public void setQueueTable(String queueTable) {
        this.queueTable = queueTable;
    }

    /**
     * Getter for <code>queue_sharding.last_key</code>.
     */
    public String getLastKey() {
        return this.lastKey;
    }

    /**
     * Setter for <code>queue_sharding.last_key</code>.
     */
    public void setLastKey(String lastKey) {
        this.lastKey = lastKey;
    }

    /**
     * Getter for <code>queue_sharding.count</code>. 分表的记录数量
     */
    public Long getCount() {
        return this.count;
    }

    /**
     * Setter for <code>queue_sharding.count</code>. 分表的记录数量
     */
    public void setCount(Long count) {
        this.count = count;
    }

    /**
     * Getter for <code>queue_sharding.max_count</code>. 分表的最大记录数,如果
     * count&gt;max_count,创建新表
     */
    public Long getMaxCount() {
        return this.maxCount;
    }

    /**
     * Setter for <code>queue_sharding.max_count</code>. 分表的最大记录数,如果
     * count&gt;max_count,创建新表
     */
    public void setMaxCount(Long maxCount) {
        this.maxCount = maxCount;
    }

    /**
     * Getter for <code>queue_sharding.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>queue_sharding.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>queue_sharding.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>queue_sharding.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>queue_sharding.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>queue_sharding.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>queue_sharding.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>queue_sharding.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>queue_sharding.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>queue_sharding.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>queue_sharding.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>queue_sharding.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QueueShardingDB (");

        sb.append(id);
        sb.append(", ").append(key);
        sb.append(", ").append(keyTime);
        sb.append(", ").append(queueTable);
        sb.append(", ").append(lastKey);
        sb.append(", ").append(count);
        sb.append(", ").append(maxCount);
        sb.append(", ").append(cuid);
        sb.append(", ").append(muid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(muName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
