/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables.pojos;


import com.ke.bella.batch.db.repo.Operator;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueueHeadDB implements Operator, Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        queue;
    private Integer       level;
    private String        lastWroteShardingKey;
    private Long          lastWroteId;
    private String        lastScannedShardingKey;
    private Long          lastScannedId;
    private Long          totalPutCnt;
    private Long          totalLoadedCnt;
    private Long          totalCompletedCnt;
    private Long          cuid;
    private Long          muid;
    private String        cuName;
    private String        muName;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public QueueHeadDB() {}

    public QueueHeadDB(QueueHeadDB value) {
        this.id = value.id;
        this.queue = value.queue;
        this.level = value.level;
        this.lastWroteShardingKey = value.lastWroteShardingKey;
        this.lastWroteId = value.lastWroteId;
        this.lastScannedShardingKey = value.lastScannedShardingKey;
        this.lastScannedId = value.lastScannedId;
        this.totalPutCnt = value.totalPutCnt;
        this.totalLoadedCnt = value.totalLoadedCnt;
        this.totalCompletedCnt = value.totalCompletedCnt;
        this.cuid = value.cuid;
        this.muid = value.muid;
        this.cuName = value.cuName;
        this.muName = value.muName;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public QueueHeadDB(
        Long          id,
        String        queue,
        Integer       level,
        String        lastWroteShardingKey,
        Long          lastWroteId,
        String        lastScannedShardingKey,
        Long          lastScannedId,
        Long          totalPutCnt,
        Long          totalLoadedCnt,
        Long          totalCompletedCnt,
        Long          cuid,
        Long          muid,
        String        cuName,
        String        muName,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.queue = queue;
        this.level = level;
        this.lastWroteShardingKey = lastWroteShardingKey;
        this.lastWroteId = lastWroteId;
        this.lastScannedShardingKey = lastScannedShardingKey;
        this.lastScannedId = lastScannedId;
        this.totalPutCnt = totalPutCnt;
        this.totalLoadedCnt = totalLoadedCnt;
        this.totalCompletedCnt = totalCompletedCnt;
        this.cuid = cuid;
        this.muid = muid;
        this.cuName = cuName;
        this.muName = muName;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>queue_head.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>queue_head.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>queue_head.queue</code>.
     */
    public String getQueue() {
        return this.queue;
    }

    /**
     * Setter for <code>queue_head.queue</code>.
     */
    public void setQueue(String queue) {
        this.queue = queue;
    }

    /**
     * Getter for <code>queue_head.level</code>.
     */
    public Integer getLevel() {
        return this.level;
    }

    /**
     * Setter for <code>queue_head.level</code>.
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * Getter for <code>queue_head.last_wrote_sharding_key</code>.
     */
    public String getLastWroteShardingKey() {
        return this.lastWroteShardingKey;
    }

    /**
     * Setter for <code>queue_head.last_wrote_sharding_key</code>.
     */
    public void setLastWroteShardingKey(String lastWroteShardingKey) {
        this.lastWroteShardingKey = lastWroteShardingKey;
    }

    /**
     * Getter for <code>queue_head.last_wrote_id</code>.
     */
    public Long getLastWroteId() {
        return this.lastWroteId;
    }

    /**
     * Setter for <code>queue_head.last_wrote_id</code>.
     */
    public void setLastWroteId(Long lastWroteId) {
        this.lastWroteId = lastWroteId;
    }

    /**
     * Getter for <code>queue_head.last_scanned_sharding_key</code>.
     */
    public String getLastScannedShardingKey() {
        return this.lastScannedShardingKey;
    }

    /**
     * Setter for <code>queue_head.last_scanned_sharding_key</code>.
     */
    public void setLastScannedShardingKey(String lastScannedShardingKey) {
        this.lastScannedShardingKey = lastScannedShardingKey;
    }

    /**
     * Getter for <code>queue_head.last_scanned_id</code>.
     */
    public Long getLastScannedId() {
        return this.lastScannedId;
    }

    /**
     * Setter for <code>queue_head.last_scanned_id</code>.
     */
    public void setLastScannedId(Long lastScannedId) {
        this.lastScannedId = lastScannedId;
    }

    /**
     * Getter for <code>queue_head.total_put_cnt</code>.
     */
    public Long getTotalPutCnt() {
        return this.totalPutCnt;
    }

    /**
     * Setter for <code>queue_head.total_put_cnt</code>.
     */
    public void setTotalPutCnt(Long totalPutCnt) {
        this.totalPutCnt = totalPutCnt;
    }

    /**
     * Getter for <code>queue_head.total_loaded_cnt</code>.
     */
    public Long getTotalLoadedCnt() {
        return this.totalLoadedCnt;
    }

    /**
     * Setter for <code>queue_head.total_loaded_cnt</code>.
     */
    public void setTotalLoadedCnt(Long totalLoadedCnt) {
        this.totalLoadedCnt = totalLoadedCnt;
    }

    /**
     * Getter for <code>queue_head.total_completed_cnt</code>.
     */
    public Long getTotalCompletedCnt() {
        return this.totalCompletedCnt;
    }

    /**
     * Setter for <code>queue_head.total_completed_cnt</code>.
     */
    public void setTotalCompletedCnt(Long totalCompletedCnt) {
        this.totalCompletedCnt = totalCompletedCnt;
    }

    /**
     * Getter for <code>queue_head.cuid</code>.
     */
    public Long getCuid() {
        return this.cuid;
    }

    /**
     * Setter for <code>queue_head.cuid</code>.
     */
    public void setCuid(Long cuid) {
        this.cuid = cuid;
    }

    /**
     * Getter for <code>queue_head.muid</code>.
     */
    public Long getMuid() {
        return this.muid;
    }

    /**
     * Setter for <code>queue_head.muid</code>.
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * Getter for <code>queue_head.cu_name</code>.
     */
    public String getCuName() {
        return this.cuName;
    }

    /**
     * Setter for <code>queue_head.cu_name</code>.
     */
    public void setCuName(String cuName) {
        this.cuName = cuName;
    }

    /**
     * Getter for <code>queue_head.mu_name</code>.
     */
    public String getMuName() {
        return this.muName;
    }

    /**
     * Setter for <code>queue_head.mu_name</code>.
     */
    public void setMuName(String muName) {
        this.muName = muName;
    }

    /**
     * Getter for <code>queue_head.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>queue_head.ctime</code>.
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>queue_head.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>queue_head.mtime</code>.
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QueueHeadDB (");

        sb.append(id);
        sb.append(", ").append(queue);
        sb.append(", ").append(level);
        sb.append(", ").append(lastWroteShardingKey);
        sb.append(", ").append(lastWroteId);
        sb.append(", ").append(lastScannedShardingKey);
        sb.append(", ").append(lastScannedId);
        sb.append(", ").append(totalPutCnt);
        sb.append(", ").append(totalLoadedCnt);
        sb.append(", ").append(totalCompletedCnt);
        sb.append(", ").append(cuid);
        sb.append(", ").append(muid);
        sb.append(", ").append(cuName);
        sb.append(", ").append(muName);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
