/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TraceTaskShardingMappingDB implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        traceId;
    private String        shardingKey;
    private LocalDateTime ctime;
    private LocalDateTime mtime;

    public TraceTaskShardingMappingDB() {}

    public TraceTaskShardingMappingDB(TraceTaskShardingMappingDB value) {
        this.id = value.id;
        this.traceId = value.traceId;
        this.shardingKey = value.shardingKey;
        this.ctime = value.ctime;
        this.mtime = value.mtime;
    }

    public TraceTaskShardingMappingDB(
        Long          id,
        String        traceId,
        String        shardingKey,
        LocalDateTime ctime,
        LocalDateTime mtime
    ) {
        this.id = id;
        this.traceId = traceId;
        this.shardingKey = shardingKey;
        this.ctime = ctime;
        this.mtime = mtime;
    }

    /**
     * Getter for <code>trace_task_sharding_mapping.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>trace_task_sharding_mapping.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>trace_task_sharding_mapping.trace_id</code>. trace_id
     */
    public String getTraceId() {
        return this.traceId;
    }

    /**
     * Setter for <code>trace_task_sharding_mapping.trace_id</code>. trace_id
     */
    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    /**
     * Getter for <code>trace_task_sharding_mapping.sharding_key</code>. 分片
     */
    public String getShardingKey() {
        return this.shardingKey;
    }

    /**
     * Setter for <code>trace_task_sharding_mapping.sharding_key</code>. 分片
     */
    public void setShardingKey(String shardingKey) {
        this.shardingKey = shardingKey;
    }

    /**
     * Getter for <code>trace_task_sharding_mapping.ctime</code>. 创建时间
     */
    public LocalDateTime getCtime() {
        return this.ctime;
    }

    /**
     * Setter for <code>trace_task_sharding_mapping.ctime</code>. 创建时间
     */
    public void setCtime(LocalDateTime ctime) {
        this.ctime = ctime;
    }

    /**
     * Getter for <code>trace_task_sharding_mapping.mtime</code>. 修改时间
     */
    public LocalDateTime getMtime() {
        return this.mtime;
    }

    /**
     * Setter for <code>trace_task_sharding_mapping.mtime</code>. 修改时间
     */
    public void setMtime(LocalDateTime mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TraceTaskShardingMappingDB (");

        sb.append(id);
        sb.append(", ").append(traceId);
        sb.append(", ").append(shardingKey);
        sb.append(", ").append(ctime);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
