/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables.records;


import com.ke.bella.batch.db.repo.Operator;
import com.ke.bella.batch.tables.Batch;
import com.ke.bella.batch.tables.pojos.BatchDB;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchRecord extends UpdatableRecordImpl<BatchRecord> implements Operator {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>batch.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>batch.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>batch.batch_id</code>.
     */
    public void setBatchId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>batch.batch_id</code>.
     */
    public String getBatchId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>batch.endpoint</code>.
     */
    public void setEndpoint(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>batch.endpoint</code>.
     */
    public String getEndpoint() {
        return (String) get(2);
    }

    /**
     * Setter for <code>batch.ak</code>.
     */
    public void setAk(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>batch.ak</code>.
     */
    public String getAk() {
        return (String) get(3);
    }

    /**
     * Setter for <code>batch.input_file_id</code>.
     */
    public void setInputFileId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>batch.input_file_id</code>.
     */
    public String getInputFileId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>batch.completion_window</code>.
     */
    public void setCompletionWindow(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>batch.completion_window</code>.
     */
    public String getCompletionWindow() {
        return (String) get(5);
    }

    /**
     * Setter for <code>batch.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>batch.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>batch.output_file_id</code>.
     */
    public void setOutputFileId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>batch.output_file_id</code>.
     */
    public String getOutputFileId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>batch.error_file_id</code>.
     */
    public void setErrorFileId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>batch.error_file_id</code>.
     */
    public String getErrorFileId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>batch.in_progress_at</code>.
     */
    public void setInProgressAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>batch.in_progress_at</code>.
     */
    public LocalDateTime getInProgressAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>batch.expired_at</code>.
     */
    public void setExpiredAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>batch.expired_at</code>.
     */
    public LocalDateTime getExpiredAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>batch.finalizing_at</code>.
     */
    public void setFinalizingAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>batch.finalizing_at</code>.
     */
    public LocalDateTime getFinalizingAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>batch.completed_at</code>.
     */
    public void setCompletedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>batch.completed_at</code>.
     */
    public LocalDateTime getCompletedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>batch.failed_at</code>.
     */
    public void setFailedAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>batch.failed_at</code>.
     */
    public LocalDateTime getFailedAt() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>batch.cancelling_at</code>.
     */
    public void setCancellingAt(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>batch.cancelling_at</code>.
     */
    public LocalDateTime getCancellingAt() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>batch.cancelled_at</code>.
     */
    public void setCancelledAt(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>batch.cancelled_at</code>.
     */
    public LocalDateTime getCancelledAt() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>batch.request_counts_total</code>.
     */
    public void setRequestCountsTotal(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>batch.request_counts_total</code>.
     */
    public Long getRequestCountsTotal() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>batch.request_counts_completed</code>.
     */
    public void setRequestCountsCompleted(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>batch.request_counts_completed</code>.
     */
    public Long getRequestCountsCompleted() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>batch.request_counts_failed</code>.
     */
    public void setRequestCountsFailed(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>batch.request_counts_failed</code>.
     */
    public Long getRequestCountsFailed() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>batch.import_counts_failed</code>.
     */
    public void setImportCountsFailed(Long value) {
        set(19, value);
    }

    /**
     * Getter for <code>batch.import_counts_failed</code>.
     */
    public Long getImportCountsFailed() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>batch.matadata</code>.
     */
    public void setMatadata(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>batch.matadata</code>.
     */
    public String getMatadata() {
        return (String) get(20);
    }

    /**
     * Setter for <code>batch.cuid</code>.
     */
    public void setCuid(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>batch.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>batch.muid</code>.
     */
    public void setMuid(Long value) {
        set(22, value);
    }

    /**
     * Getter for <code>batch.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(22);
    }

    /**
     * Setter for <code>batch.cu_name</code>.
     */
    public void setCuName(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>batch.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(23);
    }

    /**
     * Setter for <code>batch.mu_name</code>.
     */
    public void setMuName(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>batch.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(24);
    }

    /**
     * Setter for <code>batch.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(25, value);
    }

    /**
     * Getter for <code>batch.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(25);
    }

    /**
     * Setter for <code>batch.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(26, value);
    }

    /**
     * Getter for <code>batch.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(26);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BatchRecord
     */
    public BatchRecord() {
        super(Batch.BATCH);
    }

    /**
     * Create a detached, initialised BatchRecord
     */
    public BatchRecord(Long id, String batchId, String endpoint, String ak, String inputFileId, String completionWindow, String status, String outputFileId, String errorFileId, LocalDateTime inProgressAt, LocalDateTime expiredAt, LocalDateTime finalizingAt, LocalDateTime completedAt, LocalDateTime failedAt, LocalDateTime cancellingAt, LocalDateTime cancelledAt, Long requestCountsTotal, Long requestCountsCompleted, Long requestCountsFailed, Long importCountsFailed, String matadata, Long cuid, Long muid, String cuName, String muName, LocalDateTime ctime, LocalDateTime mtime) {
        super(Batch.BATCH);

        setId(id);
        setBatchId(batchId);
        setEndpoint(endpoint);
        setAk(ak);
        setInputFileId(inputFileId);
        setCompletionWindow(completionWindow);
        setStatus(status);
        setOutputFileId(outputFileId);
        setErrorFileId(errorFileId);
        setInProgressAt(inProgressAt);
        setExpiredAt(expiredAt);
        setFinalizingAt(finalizingAt);
        setCompletedAt(completedAt);
        setFailedAt(failedAt);
        setCancellingAt(cancellingAt);
        setCancelledAt(cancelledAt);
        setRequestCountsTotal(requestCountsTotal);
        setRequestCountsCompleted(requestCountsCompleted);
        setRequestCountsFailed(requestCountsFailed);
        setImportCountsFailed(importCountsFailed);
        setMatadata(matadata);
        setCuid(cuid);
        setMuid(muid);
        setCuName(cuName);
        setMuName(muName);
        setCtime(ctime);
        setMtime(mtime);
    }

    /**
     * Create a detached, initialised BatchRecord
     */
    public BatchRecord(BatchDB value) {
        super(Batch.BATCH);

        if (value != null) {
            setId(value.getId());
            setBatchId(value.getBatchId());
            setEndpoint(value.getEndpoint());
            setAk(value.getAk());
            setInputFileId(value.getInputFileId());
            setCompletionWindow(value.getCompletionWindow());
            setStatus(value.getStatus());
            setOutputFileId(value.getOutputFileId());
            setErrorFileId(value.getErrorFileId());
            setInProgressAt(value.getInProgressAt());
            setExpiredAt(value.getExpiredAt());
            setFinalizingAt(value.getFinalizingAt());
            setCompletedAt(value.getCompletedAt());
            setFailedAt(value.getFailedAt());
            setCancellingAt(value.getCancellingAt());
            setCancelledAt(value.getCancelledAt());
            setRequestCountsTotal(value.getRequestCountsTotal());
            setRequestCountsCompleted(value.getRequestCountsCompleted());
            setRequestCountsFailed(value.getRequestCountsFailed());
            setImportCountsFailed(value.getImportCountsFailed());
            setMatadata(value.getMatadata());
            setCuid(value.getCuid());
            setMuid(value.getMuid());
            setCuName(value.getCuName());
            setMuName(value.getMuName());
            setCtime(value.getCtime());
            setMtime(value.getMtime());
        }
    }
}
