/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables.records;


import com.ke.bella.batch.db.repo.Operator;
import com.ke.bella.batch.tables.Queue;
import com.ke.bella.batch.tables.pojos.QueueDB;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueueRecord extends UpdatableRecordImpl<QueueRecord> implements Operator, Record21<Long, String, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, String, Long, Long, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>queue.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>queue.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>queue.task_id</code>.
     */
    public void setTaskId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>queue.task_id</code>.
     */
    public String getTaskId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>queue.custom_id</code>.
     */
    public void setCustomId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>queue.custom_id</code>.
     */
    public String getCustomId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>queue.queue</code>.
     */
    public void setQueue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>queue.queue</code>.
     */
    public String getQueue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>queue.endpoint</code>.
     */
    public void setEndpoint(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>queue.endpoint</code>.
     */
    public String getEndpoint() {
        return (String) get(4);
    }

    /**
     * Setter for <code>queue.ak</code>.
     */
    public void setAk(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>queue.ak</code>.
     */
    public String getAk() {
        return (String) get(5);
    }

    /**
     * Setter for <code>queue.batch_id</code>.
     */
    public void setBatchId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>queue.batch_id</code>.
     */
    public String getBatchId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>queue.input_data</code>.
     */
    public void setInputData(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>queue.input_data</code>.
     */
    public String getInputData() {
        return (String) get(7);
    }

    /**
     * Setter for <code>queue.input_file_id</code>.
     */
    public void setInputFileId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>queue.input_file_id</code>.
     */
    public String getInputFileId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>queue.output_data</code>.
     */
    public void setOutputData(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>queue.output_data</code>.
     */
    public String getOutputData() {
        return (String) get(9);
    }

    /**
     * Setter for <code>queue.output_file_id</code>.
     */
    public void setOutputFileId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>queue.output_file_id</code>.
     */
    public String getOutputFileId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>queue.status</code>. waiting: 等待中, queued: 已入队, 
     * succeeded: 成功, timeout: 超时, cancelled: 已取消
     */
    public void setStatus(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>queue.status</code>. waiting: 等待中, queued: 已入队, 
     * succeeded: 成功, timeout: 超时, cancelled: 已取消
     */
    public String getStatus() {
        return (String) get(11);
    }

    /**
     * Setter for <code>queue.callback_url</code>.
     */
    public void setCallbackUrl(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>queue.callback_url</code>.
     */
    public String getCallbackUrl() {
        return (String) get(12);
    }

    /**
     * Setter for <code>queue.expired_at</code>.
     */
    public void setExpiredAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>queue.expired_at</code>.
     */
    public LocalDateTime getExpiredAt() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>queue.trace_id</code>.
     */
    public void setTraceId(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>queue.trace_id</code>.
     */
    public String getTraceId() {
        return (String) get(14);
    }

    /**
     * Setter for <code>queue.cuid</code>.
     */
    public void setCuid(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>queue.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>queue.muid</code>.
     */
    public void setMuid(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>queue.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>queue.cu_name</code>.
     */
    public void setCuName(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>queue.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(17);
    }

    /**
     * Setter for <code>queue.mu_name</code>.
     */
    public void setMuName(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>queue.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(18);
    }

    /**
     * Setter for <code>queue.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(19, value);
    }

    /**
     * Getter for <code>queue.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(19);
    }

    /**
     * Setter for <code>queue.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>queue.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row21<Long, String, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, String, Long, Long, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    @Override
    public Row21<Long, String, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, String, Long, Long, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row21) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Queue.QUEUE.ID;
    }

    @Override
    public Field<String> field2() {
        return Queue.QUEUE.TASK_ID;
    }

    @Override
    public Field<String> field3() {
        return Queue.QUEUE.CUSTOM_ID;
    }

    @Override
    public Field<String> field4() {
        return Queue.QUEUE.QUEUE_;
    }

    @Override
    public Field<String> field5() {
        return Queue.QUEUE.ENDPOINT;
    }

    @Override
    public Field<String> field6() {
        return Queue.QUEUE.AK;
    }

    @Override
    public Field<String> field7() {
        return Queue.QUEUE.BATCH_ID;
    }

    @Override
    public Field<String> field8() {
        return Queue.QUEUE.INPUT_DATA;
    }

    @Override
    public Field<String> field9() {
        return Queue.QUEUE.INPUT_FILE_ID;
    }

    @Override
    public Field<String> field10() {
        return Queue.QUEUE.OUTPUT_DATA;
    }

    @Override
    public Field<String> field11() {
        return Queue.QUEUE.OUTPUT_FILE_ID;
    }

    @Override
    public Field<String> field12() {
        return Queue.QUEUE.STATUS;
    }

    @Override
    public Field<String> field13() {
        return Queue.QUEUE.CALLBACK_URL;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return Queue.QUEUE.EXPIRED_AT;
    }

    @Override
    public Field<String> field15() {
        return Queue.QUEUE.TRACE_ID;
    }

    @Override
    public Field<Long> field16() {
        return Queue.QUEUE.CUID;
    }

    @Override
    public Field<Long> field17() {
        return Queue.QUEUE.MUID;
    }

    @Override
    public Field<String> field18() {
        return Queue.QUEUE.CU_NAME;
    }

    @Override
    public Field<String> field19() {
        return Queue.QUEUE.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field20() {
        return Queue.QUEUE.CTIME;
    }

    @Override
    public Field<LocalDateTime> field21() {
        return Queue.QUEUE.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTaskId();
    }

    @Override
    public String component3() {
        return getCustomId();
    }

    @Override
    public String component4() {
        return getQueue();
    }

    @Override
    public String component5() {
        return getEndpoint();
    }

    @Override
    public String component6() {
        return getAk();
    }

    @Override
    public String component7() {
        return getBatchId();
    }

    @Override
    public String component8() {
        return getInputData();
    }

    @Override
    public String component9() {
        return getInputFileId();
    }

    @Override
    public String component10() {
        return getOutputData();
    }

    @Override
    public String component11() {
        return getOutputFileId();
    }

    @Override
    public String component12() {
        return getStatus();
    }

    @Override
    public String component13() {
        return getCallbackUrl();
    }

    @Override
    public LocalDateTime component14() {
        return getExpiredAt();
    }

    @Override
    public String component15() {
        return getTraceId();
    }

    @Override
    public Long component16() {
        return getCuid();
    }

    @Override
    public Long component17() {
        return getMuid();
    }

    @Override
    public String component18() {
        return getCuName();
    }

    @Override
    public String component19() {
        return getMuName();
    }

    @Override
    public LocalDateTime component20() {
        return getCtime();
    }

    @Override
    public LocalDateTime component21() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTaskId();
    }

    @Override
    public String value3() {
        return getCustomId();
    }

    @Override
    public String value4() {
        return getQueue();
    }

    @Override
    public String value5() {
        return getEndpoint();
    }

    @Override
    public String value6() {
        return getAk();
    }

    @Override
    public String value7() {
        return getBatchId();
    }

    @Override
    public String value8() {
        return getInputData();
    }

    @Override
    public String value9() {
        return getInputFileId();
    }

    @Override
    public String value10() {
        return getOutputData();
    }

    @Override
    public String value11() {
        return getOutputFileId();
    }

    @Override
    public String value12() {
        return getStatus();
    }

    @Override
    public String value13() {
        return getCallbackUrl();
    }

    @Override
    public LocalDateTime value14() {
        return getExpiredAt();
    }

    @Override
    public String value15() {
        return getTraceId();
    }

    @Override
    public Long value16() {
        return getCuid();
    }

    @Override
    public Long value17() {
        return getMuid();
    }

    @Override
    public String value18() {
        return getCuName();
    }

    @Override
    public String value19() {
        return getMuName();
    }

    @Override
    public LocalDateTime value20() {
        return getCtime();
    }

    @Override
    public LocalDateTime value21() {
        return getMtime();
    }

    @Override
    public QueueRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public QueueRecord value2(String value) {
        setTaskId(value);
        return this;
    }

    @Override
    public QueueRecord value3(String value) {
        setCustomId(value);
        return this;
    }

    @Override
    public QueueRecord value4(String value) {
        setQueue(value);
        return this;
    }

    @Override
    public QueueRecord value5(String value) {
        setEndpoint(value);
        return this;
    }

    @Override
    public QueueRecord value6(String value) {
        setAk(value);
        return this;
    }

    @Override
    public QueueRecord value7(String value) {
        setBatchId(value);
        return this;
    }

    @Override
    public QueueRecord value8(String value) {
        setInputData(value);
        return this;
    }

    @Override
    public QueueRecord value9(String value) {
        setInputFileId(value);
        return this;
    }

    @Override
    public QueueRecord value10(String value) {
        setOutputData(value);
        return this;
    }

    @Override
    public QueueRecord value11(String value) {
        setOutputFileId(value);
        return this;
    }

    @Override
    public QueueRecord value12(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public QueueRecord value13(String value) {
        setCallbackUrl(value);
        return this;
    }

    @Override
    public QueueRecord value14(LocalDateTime value) {
        setExpiredAt(value);
        return this;
    }

    @Override
    public QueueRecord value15(String value) {
        setTraceId(value);
        return this;
    }

    @Override
    public QueueRecord value16(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public QueueRecord value17(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public QueueRecord value18(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public QueueRecord value19(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public QueueRecord value20(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public QueueRecord value21(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public QueueRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, LocalDateTime value14, String value15, Long value16, Long value17, String value18, String value19, LocalDateTime value20, LocalDateTime value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QueueRecord
     */
    public QueueRecord() {
        super(Queue.QUEUE);
    }

    /**
     * Create a detached, initialised QueueRecord
     */
    public QueueRecord(Long id, String taskId, String customId, String queue, String endpoint, String ak, String batchId, String inputData, String inputFileId, String outputData, String outputFileId, String status, String callbackUrl, LocalDateTime expiredAt, String traceId, Long cuid, Long muid, String cuName, String muName, LocalDateTime ctime, LocalDateTime mtime) {
        super(Queue.QUEUE);

        setId(id);
        setTaskId(taskId);
        setCustomId(customId);
        setQueue(queue);
        setEndpoint(endpoint);
        setAk(ak);
        setBatchId(batchId);
        setInputData(inputData);
        setInputFileId(inputFileId);
        setOutputData(outputData);
        setOutputFileId(outputFileId);
        setStatus(status);
        setCallbackUrl(callbackUrl);
        setExpiredAt(expiredAt);
        setTraceId(traceId);
        setCuid(cuid);
        setMuid(muid);
        setCuName(cuName);
        setMuName(muName);
        setCtime(ctime);
        setMtime(mtime);
    }

    /**
     * Create a detached, initialised QueueRecord
     */
    public QueueRecord(QueueDB value) {
        super(Queue.QUEUE);

        if (value != null) {
            setId(value.getId());
            setTaskId(value.getTaskId());
            setCustomId(value.getCustomId());
            setQueue(value.getQueue());
            setEndpoint(value.getEndpoint());
            setAk(value.getAk());
            setBatchId(value.getBatchId());
            setInputData(value.getInputData());
            setInputFileId(value.getInputFileId());
            setOutputData(value.getOutputData());
            setOutputFileId(value.getOutputFileId());
            setStatus(value.getStatus());
            setCallbackUrl(value.getCallbackUrl());
            setExpiredAt(value.getExpiredAt());
            setTraceId(value.getTraceId());
            setCuid(value.getCuid());
            setMuid(value.getMuid());
            setCuName(value.getCuName());
            setMuName(value.getMuName());
            setCtime(value.getCtime());
            setMtime(value.getMtime());
        }
    }
}
