/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables.records;


import com.ke.bella.batch.db.repo.Operator;
import com.ke.bella.batch.tables.QueueSharding;
import com.ke.bella.batch.tables.pojos.QueueShardingDB;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueueShardingRecord extends UpdatableRecordImpl<QueueShardingRecord> implements Operator, Record13<Long, String, LocalDateTime, String, String, Long, Long, Long, Long, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>queue_sharding.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>queue_sharding.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>queue_sharding.key</code>. 分表的标识
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>queue_sharding.key</code>. 分表的标识
     */
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>queue_sharding.key_time</code>.
     */
    public void setKeyTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>queue_sharding.key_time</code>.
     */
    public LocalDateTime getKeyTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>queue_sharding.queue_table</code>.
     */
    public void setQueueTable(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>queue_sharding.queue_table</code>.
     */
    public String getQueueTable() {
        return (String) get(3);
    }

    /**
     * Setter for <code>queue_sharding.last_key</code>.
     */
    public void setLastKey(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>queue_sharding.last_key</code>.
     */
    public String getLastKey() {
        return (String) get(4);
    }

    /**
     * Setter for <code>queue_sharding.count</code>. 分表的记录数量
     */
    public void setCount(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>queue_sharding.count</code>. 分表的记录数量
     */
    public Long getCount() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>queue_sharding.max_count</code>. 分表的最大记录数,如果
     * count&gt;max_count,创建新表
     */
    public void setMaxCount(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>queue_sharding.max_count</code>. 分表的最大记录数,如果
     * count&gt;max_count,创建新表
     */
    public Long getMaxCount() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>queue_sharding.cuid</code>.
     */
    public void setCuid(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>queue_sharding.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>queue_sharding.muid</code>.
     */
    public void setMuid(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>queue_sharding.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>queue_sharding.cu_name</code>.
     */
    public void setCuName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>queue_sharding.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>queue_sharding.mu_name</code>.
     */
    public void setMuName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>queue_sharding.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>queue_sharding.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>queue_sharding.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>queue_sharding.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>queue_sharding.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, LocalDateTime, String, String, Long, Long, Long, Long, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, String, LocalDateTime, String, String, Long, Long, Long, Long, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return QueueSharding.QUEUE_SHARDING.ID;
    }

    @Override
    public Field<String> field2() {
        return QueueSharding.QUEUE_SHARDING.KEY;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return QueueSharding.QUEUE_SHARDING.KEY_TIME;
    }

    @Override
    public Field<String> field4() {
        return QueueSharding.QUEUE_SHARDING.QUEUE_TABLE;
    }

    @Override
    public Field<String> field5() {
        return QueueSharding.QUEUE_SHARDING.LAST_KEY;
    }

    @Override
    public Field<Long> field6() {
        return QueueSharding.QUEUE_SHARDING.COUNT;
    }

    @Override
    public Field<Long> field7() {
        return QueueSharding.QUEUE_SHARDING.MAX_COUNT;
    }

    @Override
    public Field<Long> field8() {
        return QueueSharding.QUEUE_SHARDING.CUID;
    }

    @Override
    public Field<Long> field9() {
        return QueueSharding.QUEUE_SHARDING.MUID;
    }

    @Override
    public Field<String> field10() {
        return QueueSharding.QUEUE_SHARDING.CU_NAME;
    }

    @Override
    public Field<String> field11() {
        return QueueSharding.QUEUE_SHARDING.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return QueueSharding.QUEUE_SHARDING.CTIME;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return QueueSharding.QUEUE_SHARDING.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getKey();
    }

    @Override
    public LocalDateTime component3() {
        return getKeyTime();
    }

    @Override
    public String component4() {
        return getQueueTable();
    }

    @Override
    public String component5() {
        return getLastKey();
    }

    @Override
    public Long component6() {
        return getCount();
    }

    @Override
    public Long component7() {
        return getMaxCount();
    }

    @Override
    public Long component8() {
        return getCuid();
    }

    @Override
    public Long component9() {
        return getMuid();
    }

    @Override
    public String component10() {
        return getCuName();
    }

    @Override
    public String component11() {
        return getMuName();
    }

    @Override
    public LocalDateTime component12() {
        return getCtime();
    }

    @Override
    public LocalDateTime component13() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getKey();
    }

    @Override
    public LocalDateTime value3() {
        return getKeyTime();
    }

    @Override
    public String value4() {
        return getQueueTable();
    }

    @Override
    public String value5() {
        return getLastKey();
    }

    @Override
    public Long value6() {
        return getCount();
    }

    @Override
    public Long value7() {
        return getMaxCount();
    }

    @Override
    public Long value8() {
        return getCuid();
    }

    @Override
    public Long value9() {
        return getMuid();
    }

    @Override
    public String value10() {
        return getCuName();
    }

    @Override
    public String value11() {
        return getMuName();
    }

    @Override
    public LocalDateTime value12() {
        return getCtime();
    }

    @Override
    public LocalDateTime value13() {
        return getMtime();
    }

    @Override
    public QueueShardingRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public QueueShardingRecord value2(String value) {
        setKey(value);
        return this;
    }

    @Override
    public QueueShardingRecord value3(LocalDateTime value) {
        setKeyTime(value);
        return this;
    }

    @Override
    public QueueShardingRecord value4(String value) {
        setQueueTable(value);
        return this;
    }

    @Override
    public QueueShardingRecord value5(String value) {
        setLastKey(value);
        return this;
    }

    @Override
    public QueueShardingRecord value6(Long value) {
        setCount(value);
        return this;
    }

    @Override
    public QueueShardingRecord value7(Long value) {
        setMaxCount(value);
        return this;
    }

    @Override
    public QueueShardingRecord value8(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public QueueShardingRecord value9(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public QueueShardingRecord value10(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public QueueShardingRecord value11(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public QueueShardingRecord value12(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public QueueShardingRecord value13(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public QueueShardingRecord values(Long value1, String value2, LocalDateTime value3, String value4, String value5, Long value6, Long value7, Long value8, Long value9, String value10, String value11, LocalDateTime value12, LocalDateTime value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QueueShardingRecord
     */
    public QueueShardingRecord() {
        super(QueueSharding.QUEUE_SHARDING);
    }

    /**
     * Create a detached, initialised QueueShardingRecord
     */
    public QueueShardingRecord(Long id, String key, LocalDateTime keyTime, String queueTable, String lastKey, Long count, Long maxCount, Long cuid, Long muid, String cuName, String muName, LocalDateTime ctime, LocalDateTime mtime) {
        super(QueueSharding.QUEUE_SHARDING);

        setId(id);
        setKey(key);
        setKeyTime(keyTime);
        setQueueTable(queueTable);
        setLastKey(lastKey);
        setCount(count);
        setMaxCount(maxCount);
        setCuid(cuid);
        setMuid(muid);
        setCuName(cuName);
        setMuName(muName);
        setCtime(ctime);
        setMtime(mtime);
    }

    /**
     * Create a detached, initialised QueueShardingRecord
     */
    public QueueShardingRecord(QueueShardingDB value) {
        super(QueueSharding.QUEUE_SHARDING);

        if (value != null) {
            setId(value.getId());
            setKey(value.getKey());
            setKeyTime(value.getKeyTime());
            setQueueTable(value.getQueueTable());
            setLastKey(value.getLastKey());
            setCount(value.getCount());
            setMaxCount(value.getMaxCount());
            setCuid(value.getCuid());
            setMuid(value.getMuid());
            setCuName(value.getCuName());
            setMuName(value.getMuName());
            setCtime(value.getCtime());
            setMtime(value.getMtime());
        }
    }
}
