/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables.records;


import com.ke.bella.batch.db.repo.Operator;
import com.ke.bella.batch.tables.QueueMetadata;
import com.ke.bella.batch.tables.pojos.QueueMetadataDB;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueueMetadataRecord extends UpdatableRecordImpl<QueueMetadataRecord> implements Operator, Record10<Long, String, String, Integer, Long, Long, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>queue_metadata.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>queue_metadata.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>queue_metadata.queue</code>.
     */
    public void setQueue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>queue_metadata.queue</code>.
     */
    public String getQueue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>queue_metadata.endpoint</code>.
     */
    public void setEndpoint(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>queue_metadata.endpoint</code>.
     */
    public String getEndpoint() {
        return (String) get(2);
    }

    /**
     * Setter for <code>queue_metadata.enable_take_log</code>. 是否开启打印take日志
     */
    public void setEnableTakeLog(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>queue_metadata.enable_take_log</code>. 是否开启打印take日志
     */
    public Integer getEnableTakeLog() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>queue_metadata.cuid</code>.
     */
    public void setCuid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>queue_metadata.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>queue_metadata.muid</code>.
     */
    public void setMuid(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>queue_metadata.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>queue_metadata.cu_name</code>.
     */
    public void setCuName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>queue_metadata.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>queue_metadata.mu_name</code>.
     */
    public void setMuName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>queue_metadata.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>queue_metadata.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>queue_metadata.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>queue_metadata.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>queue_metadata.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, Integer, Long, Long, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, String, Integer, Long, Long, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return QueueMetadata.QUEUE_METADATA.ID;
    }

    @Override
    public Field<String> field2() {
        return QueueMetadata.QUEUE_METADATA.QUEUE;
    }

    @Override
    public Field<String> field3() {
        return QueueMetadata.QUEUE_METADATA.ENDPOINT;
    }

    @Override
    public Field<Integer> field4() {
        return QueueMetadata.QUEUE_METADATA.ENABLE_TAKE_LOG;
    }

    @Override
    public Field<Long> field5() {
        return QueueMetadata.QUEUE_METADATA.CUID;
    }

    @Override
    public Field<Long> field6() {
        return QueueMetadata.QUEUE_METADATA.MUID;
    }

    @Override
    public Field<String> field7() {
        return QueueMetadata.QUEUE_METADATA.CU_NAME;
    }

    @Override
    public Field<String> field8() {
        return QueueMetadata.QUEUE_METADATA.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return QueueMetadata.QUEUE_METADATA.CTIME;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return QueueMetadata.QUEUE_METADATA.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getQueue();
    }

    @Override
    public String component3() {
        return getEndpoint();
    }

    @Override
    public Integer component4() {
        return getEnableTakeLog();
    }

    @Override
    public Long component5() {
        return getCuid();
    }

    @Override
    public Long component6() {
        return getMuid();
    }

    @Override
    public String component7() {
        return getCuName();
    }

    @Override
    public String component8() {
        return getMuName();
    }

    @Override
    public LocalDateTime component9() {
        return getCtime();
    }

    @Override
    public LocalDateTime component10() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getQueue();
    }

    @Override
    public String value3() {
        return getEndpoint();
    }

    @Override
    public Integer value4() {
        return getEnableTakeLog();
    }

    @Override
    public Long value5() {
        return getCuid();
    }

    @Override
    public Long value6() {
        return getMuid();
    }

    @Override
    public String value7() {
        return getCuName();
    }

    @Override
    public String value8() {
        return getMuName();
    }

    @Override
    public LocalDateTime value9() {
        return getCtime();
    }

    @Override
    public LocalDateTime value10() {
        return getMtime();
    }

    @Override
    public QueueMetadataRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public QueueMetadataRecord value2(String value) {
        setQueue(value);
        return this;
    }

    @Override
    public QueueMetadataRecord value3(String value) {
        setEndpoint(value);
        return this;
    }

    @Override
    public QueueMetadataRecord value4(Integer value) {
        setEnableTakeLog(value);
        return this;
    }

    @Override
    public QueueMetadataRecord value5(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public QueueMetadataRecord value6(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public QueueMetadataRecord value7(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public QueueMetadataRecord value8(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public QueueMetadataRecord value9(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public QueueMetadataRecord value10(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public QueueMetadataRecord values(Long value1, String value2, String value3, Integer value4, Long value5, Long value6, String value7, String value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QueueMetadataRecord
     */
    public QueueMetadataRecord() {
        super(QueueMetadata.QUEUE_METADATA);
    }

    /**
     * Create a detached, initialised QueueMetadataRecord
     */
    public QueueMetadataRecord(Long id, String queue, String endpoint, Integer enableTakeLog, Long cuid, Long muid, String cuName, String muName, LocalDateTime ctime, LocalDateTime mtime) {
        super(QueueMetadata.QUEUE_METADATA);

        setId(id);
        setQueue(queue);
        setEndpoint(endpoint);
        setEnableTakeLog(enableTakeLog);
        setCuid(cuid);
        setMuid(muid);
        setCuName(cuName);
        setMuName(muName);
        setCtime(ctime);
        setMtime(mtime);
    }

    /**
     * Create a detached, initialised QueueMetadataRecord
     */
    public QueueMetadataRecord(QueueMetadataDB value) {
        super(QueueMetadata.QUEUE_METADATA);

        if (value != null) {
            setId(value.getId());
            setQueue(value.getQueue());
            setEndpoint(value.getEndpoint());
            setEnableTakeLog(value.getEnableTakeLog());
            setCuid(value.getCuid());
            setMuid(value.getMuid());
            setCuName(value.getCuName());
            setMuName(value.getMuName());
            setCtime(value.getCtime());
            setMtime(value.getMtime());
        }
    }
}
