/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables.records;


import com.ke.bella.batch.db.repo.Operator;
import com.ke.bella.batch.tables.QueueHead;
import com.ke.bella.batch.tables.pojos.QueueHeadDB;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueueHeadRecord extends UpdatableRecordImpl<QueueHeadRecord> implements Operator, Record16<Long, String, Integer, String, Long, String, Long, Long, Long, Long, Long, Long, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>queue_head.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>queue_head.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>queue_head.queue</code>.
     */
    public void setQueue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>queue_head.queue</code>.
     */
    public String getQueue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>queue_head.level</code>.
     */
    public void setLevel(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>queue_head.level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>queue_head.last_wrote_sharding_key</code>.
     */
    public void setLastWroteShardingKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>queue_head.last_wrote_sharding_key</code>.
     */
    public String getLastWroteShardingKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>queue_head.last_wrote_id</code>.
     */
    public void setLastWroteId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>queue_head.last_wrote_id</code>.
     */
    public Long getLastWroteId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>queue_head.last_scanned_sharding_key</code>.
     */
    public void setLastScannedShardingKey(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>queue_head.last_scanned_sharding_key</code>.
     */
    public String getLastScannedShardingKey() {
        return (String) get(5);
    }

    /**
     * Setter for <code>queue_head.last_scanned_id</code>.
     */
    public void setLastScannedId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>queue_head.last_scanned_id</code>.
     */
    public Long getLastScannedId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>queue_head.total_put_cnt</code>.
     */
    public void setTotalPutCnt(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>queue_head.total_put_cnt</code>.
     */
    public Long getTotalPutCnt() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>queue_head.total_loaded_cnt</code>.
     */
    public void setTotalLoadedCnt(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>queue_head.total_loaded_cnt</code>.
     */
    public Long getTotalLoadedCnt() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>queue_head.total_completed_cnt</code>.
     */
    public void setTotalCompletedCnt(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>queue_head.total_completed_cnt</code>.
     */
    public Long getTotalCompletedCnt() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>queue_head.cuid</code>.
     */
    public void setCuid(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>queue_head.cuid</code>.
     */
    public Long getCuid() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>queue_head.muid</code>.
     */
    public void setMuid(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>queue_head.muid</code>.
     */
    public Long getMuid() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>queue_head.cu_name</code>.
     */
    public void setCuName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>queue_head.cu_name</code>.
     */
    public String getCuName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>queue_head.mu_name</code>.
     */
    public void setMuName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>queue_head.mu_name</code>.
     */
    public String getMuName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>queue_head.ctime</code>.
     */
    public void setCtime(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>queue_head.ctime</code>.
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>queue_head.mtime</code>.
     */
    public void setMtime(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>queue_head.mtime</code>.
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Long, String, Integer, String, Long, String, Long, Long, Long, Long, Long, Long, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Long, String, Integer, String, Long, String, Long, Long, Long, Long, Long, Long, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return QueueHead.QUEUE_HEAD.ID;
    }

    @Override
    public Field<String> field2() {
        return QueueHead.QUEUE_HEAD.QUEUE;
    }

    @Override
    public Field<Integer> field3() {
        return QueueHead.QUEUE_HEAD.LEVEL;
    }

    @Override
    public Field<String> field4() {
        return QueueHead.QUEUE_HEAD.LAST_WROTE_SHARDING_KEY;
    }

    @Override
    public Field<Long> field5() {
        return QueueHead.QUEUE_HEAD.LAST_WROTE_ID;
    }

    @Override
    public Field<String> field6() {
        return QueueHead.QUEUE_HEAD.LAST_SCANNED_SHARDING_KEY;
    }

    @Override
    public Field<Long> field7() {
        return QueueHead.QUEUE_HEAD.LAST_SCANNED_ID;
    }

    @Override
    public Field<Long> field8() {
        return QueueHead.QUEUE_HEAD.TOTAL_PUT_CNT;
    }

    @Override
    public Field<Long> field9() {
        return QueueHead.QUEUE_HEAD.TOTAL_LOADED_CNT;
    }

    @Override
    public Field<Long> field10() {
        return QueueHead.QUEUE_HEAD.TOTAL_COMPLETED_CNT;
    }

    @Override
    public Field<Long> field11() {
        return QueueHead.QUEUE_HEAD.CUID;
    }

    @Override
    public Field<Long> field12() {
        return QueueHead.QUEUE_HEAD.MUID;
    }

    @Override
    public Field<String> field13() {
        return QueueHead.QUEUE_HEAD.CU_NAME;
    }

    @Override
    public Field<String> field14() {
        return QueueHead.QUEUE_HEAD.MU_NAME;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return QueueHead.QUEUE_HEAD.CTIME;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return QueueHead.QUEUE_HEAD.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getQueue();
    }

    @Override
    public Integer component3() {
        return getLevel();
    }

    @Override
    public String component4() {
        return getLastWroteShardingKey();
    }

    @Override
    public Long component5() {
        return getLastWroteId();
    }

    @Override
    public String component6() {
        return getLastScannedShardingKey();
    }

    @Override
    public Long component7() {
        return getLastScannedId();
    }

    @Override
    public Long component8() {
        return getTotalPutCnt();
    }

    @Override
    public Long component9() {
        return getTotalLoadedCnt();
    }

    @Override
    public Long component10() {
        return getTotalCompletedCnt();
    }

    @Override
    public Long component11() {
        return getCuid();
    }

    @Override
    public Long component12() {
        return getMuid();
    }

    @Override
    public String component13() {
        return getCuName();
    }

    @Override
    public String component14() {
        return getMuName();
    }

    @Override
    public LocalDateTime component15() {
        return getCtime();
    }

    @Override
    public LocalDateTime component16() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getQueue();
    }

    @Override
    public Integer value3() {
        return getLevel();
    }

    @Override
    public String value4() {
        return getLastWroteShardingKey();
    }

    @Override
    public Long value5() {
        return getLastWroteId();
    }

    @Override
    public String value6() {
        return getLastScannedShardingKey();
    }

    @Override
    public Long value7() {
        return getLastScannedId();
    }

    @Override
    public Long value8() {
        return getTotalPutCnt();
    }

    @Override
    public Long value9() {
        return getTotalLoadedCnt();
    }

    @Override
    public Long value10() {
        return getTotalCompletedCnt();
    }

    @Override
    public Long value11() {
        return getCuid();
    }

    @Override
    public Long value12() {
        return getMuid();
    }

    @Override
    public String value13() {
        return getCuName();
    }

    @Override
    public String value14() {
        return getMuName();
    }

    @Override
    public LocalDateTime value15() {
        return getCtime();
    }

    @Override
    public LocalDateTime value16() {
        return getMtime();
    }

    @Override
    public QueueHeadRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public QueueHeadRecord value2(String value) {
        setQueue(value);
        return this;
    }

    @Override
    public QueueHeadRecord value3(Integer value) {
        setLevel(value);
        return this;
    }

    @Override
    public QueueHeadRecord value4(String value) {
        setLastWroteShardingKey(value);
        return this;
    }

    @Override
    public QueueHeadRecord value5(Long value) {
        setLastWroteId(value);
        return this;
    }

    @Override
    public QueueHeadRecord value6(String value) {
        setLastScannedShardingKey(value);
        return this;
    }

    @Override
    public QueueHeadRecord value7(Long value) {
        setLastScannedId(value);
        return this;
    }

    @Override
    public QueueHeadRecord value8(Long value) {
        setTotalPutCnt(value);
        return this;
    }

    @Override
    public QueueHeadRecord value9(Long value) {
        setTotalLoadedCnt(value);
        return this;
    }

    @Override
    public QueueHeadRecord value10(Long value) {
        setTotalCompletedCnt(value);
        return this;
    }

    @Override
    public QueueHeadRecord value11(Long value) {
        setCuid(value);
        return this;
    }

    @Override
    public QueueHeadRecord value12(Long value) {
        setMuid(value);
        return this;
    }

    @Override
    public QueueHeadRecord value13(String value) {
        setCuName(value);
        return this;
    }

    @Override
    public QueueHeadRecord value14(String value) {
        setMuName(value);
        return this;
    }

    @Override
    public QueueHeadRecord value15(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public QueueHeadRecord value16(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public QueueHeadRecord values(Long value1, String value2, Integer value3, String value4, Long value5, String value6, Long value7, Long value8, Long value9, Long value10, Long value11, Long value12, String value13, String value14, LocalDateTime value15, LocalDateTime value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QueueHeadRecord
     */
    public QueueHeadRecord() {
        super(QueueHead.QUEUE_HEAD);
    }

    /**
     * Create a detached, initialised QueueHeadRecord
     */
    public QueueHeadRecord(Long id, String queue, Integer level, String lastWroteShardingKey, Long lastWroteId, String lastScannedShardingKey, Long lastScannedId, Long totalPutCnt, Long totalLoadedCnt, Long totalCompletedCnt, Long cuid, Long muid, String cuName, String muName, LocalDateTime ctime, LocalDateTime mtime) {
        super(QueueHead.QUEUE_HEAD);

        setId(id);
        setQueue(queue);
        setLevel(level);
        setLastWroteShardingKey(lastWroteShardingKey);
        setLastWroteId(lastWroteId);
        setLastScannedShardingKey(lastScannedShardingKey);
        setLastScannedId(lastScannedId);
        setTotalPutCnt(totalPutCnt);
        setTotalLoadedCnt(totalLoadedCnt);
        setTotalCompletedCnt(totalCompletedCnt);
        setCuid(cuid);
        setMuid(muid);
        setCuName(cuName);
        setMuName(muName);
        setCtime(ctime);
        setMtime(mtime);
    }

    /**
     * Create a detached, initialised QueueHeadRecord
     */
    public QueueHeadRecord(QueueHeadDB value) {
        super(QueueHead.QUEUE_HEAD);

        if (value != null) {
            setId(value.getId());
            setQueue(value.getQueue());
            setLevel(value.getLevel());
            setLastWroteShardingKey(value.getLastWroteShardingKey());
            setLastWroteId(value.getLastWroteId());
            setLastScannedShardingKey(value.getLastScannedShardingKey());
            setLastScannedId(value.getLastScannedId());
            setTotalPutCnt(value.getTotalPutCnt());
            setTotalLoadedCnt(value.getTotalLoadedCnt());
            setTotalCompletedCnt(value.getTotalCompletedCnt());
            setCuid(value.getCuid());
            setMuid(value.getMuid());
            setCuName(value.getCuName());
            setMuName(value.getMuName());
            setCtime(value.getCtime());
            setMtime(value.getMtime());
        }
    }
}
