/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables.records;


import com.ke.bella.batch.tables.TraceTaskShardingMapping;
import com.ke.bella.batch.tables.pojos.TraceTaskShardingMappingDB;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TraceTaskShardingMappingRecord extends UpdatableRecordImpl<TraceTaskShardingMappingRecord> implements Record5<Long, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trace_task_sharding_mapping.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>trace_task_sharding_mapping.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>trace_task_sharding_mapping.trace_id</code>. trace_id
     */
    public void setTraceId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>trace_task_sharding_mapping.trace_id</code>. trace_id
     */
    public String getTraceId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>trace_task_sharding_mapping.sharding_key</code>. 分片
     */
    public void setShardingKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>trace_task_sharding_mapping.sharding_key</code>. 分片
     */
    public String getShardingKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trace_task_sharding_mapping.ctime</code>. 创建时间
     */
    public void setCtime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>trace_task_sharding_mapping.ctime</code>. 创建时间
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>trace_task_sharding_mapping.mtime</code>. 修改时间
     */
    public void setMtime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>trace_task_sharding_mapping.mtime</code>. 修改时间
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TraceTaskShardingMapping.TRACE_TASK_SHARDING_MAPPING.ID;
    }

    @Override
    public Field<String> field2() {
        return TraceTaskShardingMapping.TRACE_TASK_SHARDING_MAPPING.TRACE_ID;
    }

    @Override
    public Field<String> field3() {
        return TraceTaskShardingMapping.TRACE_TASK_SHARDING_MAPPING.SHARDING_KEY;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return TraceTaskShardingMapping.TRACE_TASK_SHARDING_MAPPING.CTIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return TraceTaskShardingMapping.TRACE_TASK_SHARDING_MAPPING.MTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTraceId();
    }

    @Override
    public String component3() {
        return getShardingKey();
    }

    @Override
    public LocalDateTime component4() {
        return getCtime();
    }

    @Override
    public LocalDateTime component5() {
        return getMtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTraceId();
    }

    @Override
    public String value3() {
        return getShardingKey();
    }

    @Override
    public LocalDateTime value4() {
        return getCtime();
    }

    @Override
    public LocalDateTime value5() {
        return getMtime();
    }

    @Override
    public TraceTaskShardingMappingRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TraceTaskShardingMappingRecord value2(String value) {
        setTraceId(value);
        return this;
    }

    @Override
    public TraceTaskShardingMappingRecord value3(String value) {
        setShardingKey(value);
        return this;
    }

    @Override
    public TraceTaskShardingMappingRecord value4(LocalDateTime value) {
        setCtime(value);
        return this;
    }

    @Override
    public TraceTaskShardingMappingRecord value5(LocalDateTime value) {
        setMtime(value);
        return this;
    }

    @Override
    public TraceTaskShardingMappingRecord values(Long value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TraceTaskShardingMappingRecord
     */
    public TraceTaskShardingMappingRecord() {
        super(TraceTaskShardingMapping.TRACE_TASK_SHARDING_MAPPING);
    }

    /**
     * Create a detached, initialised TraceTaskShardingMappingRecord
     */
    public TraceTaskShardingMappingRecord(Long id, String traceId, String shardingKey, LocalDateTime ctime, LocalDateTime mtime) {
        super(TraceTaskShardingMapping.TRACE_TASK_SHARDING_MAPPING);

        setId(id);
        setTraceId(traceId);
        setShardingKey(shardingKey);
        setCtime(ctime);
        setMtime(mtime);
    }

    /**
     * Create a detached, initialised TraceTaskShardingMappingRecord
     */
    public TraceTaskShardingMappingRecord(TraceTaskShardingMappingDB value) {
        super(TraceTaskShardingMapping.TRACE_TASK_SHARDING_MAPPING);

        if (value != null) {
            setId(value.getId());
            setTraceId(value.getTraceId());
            setShardingKey(value.getShardingKey());
            setCtime(value.getCtime());
            setMtime(value.getMtime());
        }
    }
}
