/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables;


import com.ke.bella.batch.DefaultSchema;
import com.ke.bella.batch.Indexes;
import com.ke.bella.batch.Keys;
import com.ke.bella.batch.tables.records.BatchRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Batch extends TableImpl<BatchRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>batch</code>
     */
    public static final Batch BATCH = new Batch();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BatchRecord> getRecordType() {
        return BatchRecord.class;
    }

    /**
     * The column <code>batch.id</code>.
     */
    public final TableField<BatchRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>batch.batch_id</code>.
     */
    public final TableField<BatchRecord, String> BATCH_ID = createField(DSL.name("batch_id"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>batch.endpoint</code>.
     */
    public final TableField<BatchRecord, String> ENDPOINT = createField(DSL.name("endpoint"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>batch.ak</code>.
     */
    public final TableField<BatchRecord, String> AK = createField(DSL.name("ak"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>batch.input_file_id</code>.
     */
    public final TableField<BatchRecord, String> INPUT_FILE_ID = createField(DSL.name("input_file_id"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>batch.completion_window</code>.
     */
    public final TableField<BatchRecord, String> COMPLETION_WINDOW = createField(DSL.name("completion_window"), SQLDataType.VARCHAR(8).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>batch.status</code>.
     */
    public final TableField<BatchRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("validating", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>batch.output_file_id</code>.
     */
    public final TableField<BatchRecord, String> OUTPUT_FILE_ID = createField(DSL.name("output_file_id"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>batch.error_file_id</code>.
     */
    public final TableField<BatchRecord, String> ERROR_FILE_ID = createField(DSL.name("error_file_id"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>batch.in_progress_at</code>.
     */
    public final TableField<BatchRecord, LocalDateTime> IN_PROGRESS_AT = createField(DSL.name("in_progress_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.inline("2000-01-01 00:00:00", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>batch.expired_at</code>.
     */
    public final TableField<BatchRecord, LocalDateTime> EXPIRED_AT = createField(DSL.name("expired_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.inline("2000-01-01 00:00:00", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>batch.finalizing_at</code>.
     */
    public final TableField<BatchRecord, LocalDateTime> FINALIZING_AT = createField(DSL.name("finalizing_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.inline("2000-01-01 00:00:00", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>batch.completed_at</code>.
     */
    public final TableField<BatchRecord, LocalDateTime> COMPLETED_AT = createField(DSL.name("completed_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.inline("2000-01-01 00:00:00", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>batch.failed_at</code>.
     */
    public final TableField<BatchRecord, LocalDateTime> FAILED_AT = createField(DSL.name("failed_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.inline("2000-01-01 00:00:00", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>batch.cancelling_at</code>.
     */
    public final TableField<BatchRecord, LocalDateTime> CANCELLING_AT = createField(DSL.name("cancelling_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.inline("2000-01-01 00:00:00", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>batch.cancelled_at</code>.
     */
    public final TableField<BatchRecord, LocalDateTime> CANCELLED_AT = createField(DSL.name("cancelled_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.inline("2000-01-01 00:00:00", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>batch.request_counts_total</code>.
     */
    public final TableField<BatchRecord, Long> REQUEST_COUNTS_TOTAL = createField(DSL.name("request_counts_total"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>batch.request_counts_completed</code>.
     */
    public final TableField<BatchRecord, Long> REQUEST_COUNTS_COMPLETED = createField(DSL.name("request_counts_completed"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>batch.request_counts_failed</code>.
     */
    public final TableField<BatchRecord, Long> REQUEST_COUNTS_FAILED = createField(DSL.name("request_counts_failed"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>batch.import_counts_failed</code>.
     */
    public final TableField<BatchRecord, Long> IMPORT_COUNTS_FAILED = createField(DSL.name("import_counts_failed"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>batch.matadata</code>.
     */
    public final TableField<BatchRecord, String> MATADATA = createField(DSL.name("matadata"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>batch.cuid</code>.
     */
    public final TableField<BatchRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>batch.muid</code>.
     */
    public final TableField<BatchRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>batch.cu_name</code>.
     */
    public final TableField<BatchRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>batch.mu_name</code>.
     */
    public final TableField<BatchRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>batch.ctime</code>.
     */
    public final TableField<BatchRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>batch.mtime</code>.
     */
    public final TableField<BatchRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private Batch(Name alias, Table<BatchRecord> aliased) {
        this(alias, aliased, null);
    }

    private Batch(Name alias, Table<BatchRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>batch</code> table reference
     */
    public Batch(String alias) {
        this(DSL.name(alias), BATCH);
    }

    /**
     * Create an aliased <code>batch</code> table reference
     */
    public Batch(Name alias) {
        this(alias, BATCH);
    }

    /**
     * Create a <code>batch</code> table reference
     */
    public Batch() {
        this(DSL.name("batch"), null);
    }

    public <O extends Record> Batch(Table<O> child, ForeignKey<O, BatchRecord> key) {
        super(child, key, BATCH);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.BATCH_IDX_ENDPOINT_CUID);
    }

    @Override
    public Identity<BatchRecord, Long> getIdentity() {
        return (Identity<BatchRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<BatchRecord> getPrimaryKey() {
        return Keys.KEY_BATCH_PRIMARY;
    }

    @Override
    public List<UniqueKey<BatchRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_BATCH_IDX_BATCH_ID);
    }

    @Override
    public Batch as(String alias) {
        return new Batch(DSL.name(alias), this);
    }

    @Override
    public Batch as(Name alias) {
        return new Batch(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Batch rename(String name) {
        return new Batch(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Batch rename(Name name) {
        return new Batch(name, null);
    }
}
