/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables;


import com.ke.bella.batch.DefaultSchema;
import com.ke.bella.batch.Indexes;
import com.ke.bella.batch.Keys;
import com.ke.bella.batch.tables.records.QueueShardingRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueueSharding extends TableImpl<QueueShardingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>queue_sharding</code>
     */
    public static final QueueSharding QUEUE_SHARDING = new QueueSharding();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QueueShardingRecord> getRecordType() {
        return QueueShardingRecord.class;
    }

    /**
     * The column <code>queue_sharding.id</code>.
     */
    public final TableField<QueueShardingRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>queue_sharding.key</code>. 分表的标识
     */
    public final TableField<QueueShardingRecord, String> KEY = createField(DSL.name("key"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "分表的标识");

    /**
     * The column <code>queue_sharding.key_time</code>.
     */
    public final TableField<QueueShardingRecord, LocalDateTime> KEY_TIME = createField(DSL.name("key_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.inline("2000-01-01 00:00:00", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>queue_sharding.queue_table</code>.
     */
    public final TableField<QueueShardingRecord, String> QUEUE_TABLE = createField(DSL.name("queue_table"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue_sharding.last_key</code>.
     */
    public final TableField<QueueShardingRecord, String> LAST_KEY = createField(DSL.name("last_key"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue_sharding.count</code>. 分表的记录数量
     */
    public final TableField<QueueShardingRecord, Long> COUNT = createField(DSL.name("count"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "分表的记录数量");

    /**
     * The column <code>queue_sharding.max_count</code>. 分表的最大记录数,如果
     * count&gt;max_count,创建新表
     */
    public final TableField<QueueShardingRecord, Long> MAX_COUNT = createField(DSL.name("max_count"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("20000000", SQLDataType.BIGINT)), this, "分表的最大记录数,如果 count>max_count,创建新表");

    /**
     * The column <code>queue_sharding.cuid</code>.
     */
    public final TableField<QueueShardingRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>queue_sharding.muid</code>.
     */
    public final TableField<QueueShardingRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>queue_sharding.cu_name</code>.
     */
    public final TableField<QueueShardingRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue_sharding.mu_name</code>.
     */
    public final TableField<QueueShardingRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue_sharding.ctime</code>.
     */
    public final TableField<QueueShardingRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>queue_sharding.mtime</code>.
     */
    public final TableField<QueueShardingRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private QueueSharding(Name alias, Table<QueueShardingRecord> aliased) {
        this(alias, aliased, null);
    }

    private QueueSharding(Name alias, Table<QueueShardingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>queue_sharding</code> table reference
     */
    public QueueSharding(String alias) {
        this(DSL.name(alias), QUEUE_SHARDING);
    }

    /**
     * Create an aliased <code>queue_sharding</code> table reference
     */
    public QueueSharding(Name alias) {
        this(alias, QUEUE_SHARDING);
    }

    /**
     * Create a <code>queue_sharding</code> table reference
     */
    public QueueSharding() {
        this(DSL.name("queue_sharding"), null);
    }

    public <O extends Record> QueueSharding(Table<O> child, ForeignKey<O, QueueShardingRecord> key) {
        super(child, key, QUEUE_SHARDING);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.QUEUE_SHARDING_IDX_KEY, Indexes.QUEUE_SHARDING_IDX_LAST_KEY);
    }

    @Override
    public Identity<QueueShardingRecord, Long> getIdentity() {
        return (Identity<QueueShardingRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<QueueShardingRecord> getPrimaryKey() {
        return Keys.KEY_QUEUE_SHARDING_PRIMARY;
    }

    @Override
    public List<UniqueKey<QueueShardingRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_QUEUE_SHARDING_UK_QUEUE_TABLE_KEY);
    }

    @Override
    public QueueSharding as(String alias) {
        return new QueueSharding(DSL.name(alias), this);
    }

    @Override
    public QueueSharding as(Name alias) {
        return new QueueSharding(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QueueSharding rename(String name) {
        return new QueueSharding(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QueueSharding rename(Name name) {
        return new QueueSharding(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, LocalDateTime, String, String, Long, Long, Long, Long, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
}
