/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables;


import com.ke.bella.batch.DefaultSchema;
import com.ke.bella.batch.Indexes;
import com.ke.bella.batch.Keys;
import com.ke.bella.batch.tables.records.QueueHeadRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row16;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueueHead extends TableImpl<QueueHeadRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>queue_head</code>
     */
    public static final QueueHead QUEUE_HEAD = new QueueHead();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QueueHeadRecord> getRecordType() {
        return QueueHeadRecord.class;
    }

    /**
     * The column <code>queue_head.id</code>.
     */
    public final TableField<QueueHeadRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>queue_head.queue</code>.
     */
    public final TableField<QueueHeadRecord, String> QUEUE = createField(DSL.name("queue"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue_head.level</code>.
     */
    public final TableField<QueueHeadRecord, Integer> LEVEL = createField(DSL.name("level"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>queue_head.last_wrote_sharding_key</code>.
     */
    public final TableField<QueueHeadRecord, String> LAST_WROTE_SHARDING_KEY = createField(DSL.name("last_wrote_sharding_key"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue_head.last_wrote_id</code>.
     */
    public final TableField<QueueHeadRecord, Long> LAST_WROTE_ID = createField(DSL.name("last_wrote_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>queue_head.last_scanned_sharding_key</code>.
     */
    public final TableField<QueueHeadRecord, String> LAST_SCANNED_SHARDING_KEY = createField(DSL.name("last_scanned_sharding_key"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue_head.last_scanned_id</code>.
     */
    public final TableField<QueueHeadRecord, Long> LAST_SCANNED_ID = createField(DSL.name("last_scanned_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>queue_head.total_put_cnt</code>.
     */
    public final TableField<QueueHeadRecord, Long> TOTAL_PUT_CNT = createField(DSL.name("total_put_cnt"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>queue_head.total_loaded_cnt</code>.
     */
    public final TableField<QueueHeadRecord, Long> TOTAL_LOADED_CNT = createField(DSL.name("total_loaded_cnt"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>queue_head.total_completed_cnt</code>.
     */
    public final TableField<QueueHeadRecord, Long> TOTAL_COMPLETED_CNT = createField(DSL.name("total_completed_cnt"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>queue_head.cuid</code>.
     */
    public final TableField<QueueHeadRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>queue_head.muid</code>.
     */
    public final TableField<QueueHeadRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>queue_head.cu_name</code>.
     */
    public final TableField<QueueHeadRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue_head.mu_name</code>.
     */
    public final TableField<QueueHeadRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue_head.ctime</code>.
     */
    public final TableField<QueueHeadRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>queue_head.mtime</code>.
     */
    public final TableField<QueueHeadRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private QueueHead(Name alias, Table<QueueHeadRecord> aliased) {
        this(alias, aliased, null);
    }

    private QueueHead(Name alias, Table<QueueHeadRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>queue_head</code> table reference
     */
    public QueueHead(String alias) {
        this(DSL.name(alias), QUEUE_HEAD);
    }

    /**
     * Create an aliased <code>queue_head</code> table reference
     */
    public QueueHead(Name alias) {
        this(alias, QUEUE_HEAD);
    }

    /**
     * Create a <code>queue_head</code> table reference
     */
    public QueueHead() {
        this(DSL.name("queue_head"), null);
    }

    public <O extends Record> QueueHead(Table<O> child, ForeignKey<O, QueueHeadRecord> key) {
        super(child, key, QUEUE_HEAD);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.QUEUE_HEAD_IDX_QUEUE);
    }

    @Override
    public Identity<QueueHeadRecord, Long> getIdentity() {
        return (Identity<QueueHeadRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<QueueHeadRecord> getPrimaryKey() {
        return Keys.KEY_QUEUE_HEAD_PRIMARY;
    }

    @Override
    public List<UniqueKey<QueueHeadRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_QUEUE_HEAD_UK_QUEUE_LEVEL, Keys.KEY_QUEUE_HEAD_UK_WROTE_KEY, Keys.KEY_QUEUE_HEAD_UK_SCANNED_KEY);
    }

    @Override
    public QueueHead as(String alias) {
        return new QueueHead(DSL.name(alias), this);
    }

    @Override
    public QueueHead as(Name alias) {
        return new QueueHead(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QueueHead rename(String name) {
        return new QueueHead(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QueueHead rename(Name name) {
        return new QueueHead(name, null);
    }

    // -------------------------------------------------------------------------
    // Row16 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row16<Long, String, Integer, String, Long, String, Long, Long, Long, Long, Long, Long, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row16) super.fieldsRow();
    }
}
