/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables;


import com.ke.bella.batch.DefaultSchema;
import com.ke.bella.batch.Keys;
import com.ke.bella.batch.tables.records.QueueMetadataRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueueMetadata extends TableImpl<QueueMetadataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>queue_metadata</code>
     */
    public static final QueueMetadata QUEUE_METADATA = new QueueMetadata();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QueueMetadataRecord> getRecordType() {
        return QueueMetadataRecord.class;
    }

    /**
     * The column <code>queue_metadata.id</code>.
     */
    public final TableField<QueueMetadataRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>queue_metadata.queue</code>.
     */
    public final TableField<QueueMetadataRecord, String> QUEUE = createField(DSL.name("queue"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue_metadata.endpoint</code>.
     */
    public final TableField<QueueMetadataRecord, String> ENDPOINT = createField(DSL.name("endpoint"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue_metadata.enable_take_log</code>. 是否开启打印take日志
     */
    public final TableField<QueueMetadataRecord, Integer> ENABLE_TAKE_LOG = createField(DSL.name("enable_take_log"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "是否开启打印take日志");

    /**
     * The column <code>queue_metadata.cuid</code>.
     */
    public final TableField<QueueMetadataRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>queue_metadata.muid</code>.
     */
    public final TableField<QueueMetadataRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>queue_metadata.cu_name</code>.
     */
    public final TableField<QueueMetadataRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue_metadata.mu_name</code>.
     */
    public final TableField<QueueMetadataRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue_metadata.ctime</code>.
     */
    public final TableField<QueueMetadataRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>queue_metadata.mtime</code>.
     */
    public final TableField<QueueMetadataRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private QueueMetadata(Name alias, Table<QueueMetadataRecord> aliased) {
        this(alias, aliased, null);
    }

    private QueueMetadata(Name alias, Table<QueueMetadataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>queue_metadata</code> table reference
     */
    public QueueMetadata(String alias) {
        this(DSL.name(alias), QUEUE_METADATA);
    }

    /**
     * Create an aliased <code>queue_metadata</code> table reference
     */
    public QueueMetadata(Name alias) {
        this(alias, QUEUE_METADATA);
    }

    /**
     * Create a <code>queue_metadata</code> table reference
     */
    public QueueMetadata() {
        this(DSL.name("queue_metadata"), null);
    }

    public <O extends Record> QueueMetadata(Table<O> child, ForeignKey<O, QueueMetadataRecord> key) {
        super(child, key, QUEUE_METADATA);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<QueueMetadataRecord, Long> getIdentity() {
        return (Identity<QueueMetadataRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<QueueMetadataRecord> getPrimaryKey() {
        return Keys.KEY_QUEUE_METADATA_PRIMARY;
    }

    @Override
    public List<UniqueKey<QueueMetadataRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_QUEUE_METADATA_UK_QUEUE);
    }

    @Override
    public QueueMetadata as(String alias) {
        return new QueueMetadata(DSL.name(alias), this);
    }

    @Override
    public QueueMetadata as(Name alias) {
        return new QueueMetadata(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QueueMetadata rename(String name) {
        return new QueueMetadata(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QueueMetadata rename(Name name) {
        return new QueueMetadata(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, Integer, Long, Long, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
