/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables;


import com.ke.bella.batch.DefaultSchema;
import com.ke.bella.batch.Indexes;
import com.ke.bella.batch.Keys;
import com.ke.bella.batch.tables.records.QueueRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row21;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Queue extends TableImpl<QueueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>queue</code>
     */
    public static final Queue QUEUE = new Queue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QueueRecord> getRecordType() {
        return QueueRecord.class;
    }

    /**
     * The column <code>queue.id</code>.
     */
    public final TableField<QueueRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>queue.task_id</code>.
     */
    public final TableField<QueueRecord, String> TASK_ID = createField(DSL.name("task_id"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue.custom_id</code>.
     */
    public final TableField<QueueRecord, String> CUSTOM_ID = createField(DSL.name("custom_id"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue.queue</code>.
     */
    public final TableField<QueueRecord, String> QUEUE_ = createField(DSL.name("queue"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue.endpoint</code>.
     */
    public final TableField<QueueRecord, String> ENDPOINT = createField(DSL.name("endpoint"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue.ak</code>.
     */
    public final TableField<QueueRecord, String> AK = createField(DSL.name("ak"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue.batch_id</code>.
     */
    public final TableField<QueueRecord, String> BATCH_ID = createField(DSL.name("batch_id"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue.input_data</code>.
     */
    public final TableField<QueueRecord, String> INPUT_DATA = createField(DSL.name("input_data"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>queue.input_file_id</code>.
     */
    public final TableField<QueueRecord, String> INPUT_FILE_ID = createField(DSL.name("input_file_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue.output_data</code>.
     */
    public final TableField<QueueRecord, String> OUTPUT_DATA = createField(DSL.name("output_data"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>queue.output_file_id</code>.
     */
    public final TableField<QueueRecord, String> OUTPUT_FILE_ID = createField(DSL.name("output_file_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue.status</code>. waiting: 等待中, queued: 已入队, 
     * succeeded: 成功, timeout: 超时, cancelled: 已取消
     */
    public final TableField<QueueRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.inline("waiting", SQLDataType.VARCHAR)), this, "waiting: 等待中, queued: 已入队,  succeeded: 成功, timeout: 超时, cancelled: 已取消");

    /**
     * The column <code>queue.callback_url</code>.
     */
    public final TableField<QueueRecord, String> CALLBACK_URL = createField(DSL.name("callback_url"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue.expired_at</code>.
     */
    public final TableField<QueueRecord, LocalDateTime> EXPIRED_AT = createField(DSL.name("expired_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.inline("2000-01-01 00:00:00", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>queue.trace_id</code>.
     */
    public final TableField<QueueRecord, String> TRACE_ID = createField(DSL.name("trace_id"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue.cuid</code>.
     */
    public final TableField<QueueRecord, Long> CUID = createField(DSL.name("cuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>queue.muid</code>.
     */
    public final TableField<QueueRecord, Long> MUID = createField(DSL.name("muid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>queue.cu_name</code>.
     */
    public final TableField<QueueRecord, String> CU_NAME = createField(DSL.name("cu_name"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue.mu_name</code>.
     */
    public final TableField<QueueRecord, String> MU_NAME = createField(DSL.name("mu_name"), SQLDataType.VARCHAR(256).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>queue.ctime</code>.
     */
    public final TableField<QueueRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>queue.mtime</code>.
     */
    public final TableField<QueueRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private Queue(Name alias, Table<QueueRecord> aliased) {
        this(alias, aliased, null);
    }

    private Queue(Name alias, Table<QueueRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>queue</code> table reference
     */
    public Queue(String alias) {
        this(DSL.name(alias), QUEUE);
    }

    /**
     * Create an aliased <code>queue</code> table reference
     */
    public Queue(Name alias) {
        this(alias, QUEUE);
    }

    /**
     * Create a <code>queue</code> table reference
     */
    public Queue() {
        this(DSL.name("queue"), null);
    }

    public <O extends Record> Queue(Table<O> child, ForeignKey<O, QueueRecord> key) {
        super(child, key, QUEUE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.QUEUE_IDX_BATCH_ID);
    }

    @Override
    public Identity<QueueRecord, Long> getIdentity() {
        return (Identity<QueueRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<QueueRecord> getPrimaryKey() {
        return Keys.KEY_QUEUE_PRIMARY;
    }

    @Override
    public List<UniqueKey<QueueRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_QUEUE_UK_TASK_ID);
    }

    @Override
    public Queue as(String alias) {
        return new Queue(DSL.name(alias), this);
    }

    @Override
    public Queue as(Name alias) {
        return new Queue(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Queue rename(String name) {
        return new Queue(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Queue rename(Name name) {
        return new Queue(name, null);
    }

    // -------------------------------------------------------------------------
    // Row21 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row21<Long, String, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, String, Long, Long, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row21) super.fieldsRow();
    }
}
