/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch.tables;


import com.ke.bella.batch.DefaultSchema;
import com.ke.bella.batch.Keys;
import com.ke.bella.batch.tables.records.TraceTaskShardingMappingRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TraceTaskShardingMapping extends TableImpl<TraceTaskShardingMappingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>trace_task_sharding_mapping</code>
     */
    public static final TraceTaskShardingMapping TRACE_TASK_SHARDING_MAPPING = new TraceTaskShardingMapping();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TraceTaskShardingMappingRecord> getRecordType() {
        return TraceTaskShardingMappingRecord.class;
    }

    /**
     * The column <code>trace_task_sharding_mapping.id</code>.
     */
    public final TableField<TraceTaskShardingMappingRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>trace_task_sharding_mapping.trace_id</code>. trace_id
     */
    public final TableField<TraceTaskShardingMappingRecord, String> TRACE_ID = createField(DSL.name("trace_id"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "trace_id");

    /**
     * The column <code>trace_task_sharding_mapping.sharding_key</code>. 分片
     */
    public final TableField<TraceTaskShardingMappingRecord, String> SHARDING_KEY = createField(DSL.name("sharding_key"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "分片");

    /**
     * The column <code>trace_task_sharding_mapping.ctime</code>. 创建时间
     */
    public final TableField<TraceTaskShardingMappingRecord, LocalDateTime> CTIME = createField(DSL.name("ctime"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "创建时间");

    /**
     * The column <code>trace_task_sharding_mapping.mtime</code>. 修改时间
     */
    public final TableField<TraceTaskShardingMappingRecord, LocalDateTime> MTIME = createField(DSL.name("mtime"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "修改时间");

    private TraceTaskShardingMapping(Name alias, Table<TraceTaskShardingMappingRecord> aliased) {
        this(alias, aliased, null);
    }

    private TraceTaskShardingMapping(Name alias, Table<TraceTaskShardingMappingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>trace_task_sharding_mapping</code> table
     * reference
     */
    public TraceTaskShardingMapping(String alias) {
        this(DSL.name(alias), TRACE_TASK_SHARDING_MAPPING);
    }

    /**
     * Create an aliased <code>trace_task_sharding_mapping</code> table
     * reference
     */
    public TraceTaskShardingMapping(Name alias) {
        this(alias, TRACE_TASK_SHARDING_MAPPING);
    }

    /**
     * Create a <code>trace_task_sharding_mapping</code> table reference
     */
    public TraceTaskShardingMapping() {
        this(DSL.name("trace_task_sharding_mapping"), null);
    }

    public <O extends Record> TraceTaskShardingMapping(Table<O> child, ForeignKey<O, TraceTaskShardingMappingRecord> key) {
        super(child, key, TRACE_TASK_SHARDING_MAPPING);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<TraceTaskShardingMappingRecord, Long> getIdentity() {
        return (Identity<TraceTaskShardingMappingRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TraceTaskShardingMappingRecord> getPrimaryKey() {
        return Keys.KEY_TRACE_TASK_SHARDING_MAPPING_PRIMARY;
    }

    @Override
    public List<UniqueKey<TraceTaskShardingMappingRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_TRACE_TASK_SHARDING_MAPPING_UK_TRACEID_SHARDINGKEY);
    }

    @Override
    public TraceTaskShardingMapping as(String alias) {
        return new TraceTaskShardingMapping(DSL.name(alias), this);
    }

    @Override
    public TraceTaskShardingMapping as(Name alias) {
        return new TraceTaskShardingMapping(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TraceTaskShardingMapping rename(String name) {
        return new TraceTaskShardingMapping(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TraceTaskShardingMapping rename(Name name) {
        return new TraceTaskShardingMapping(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
