/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch;


import com.ke.bella.batch.tables.Batch;
import com.ke.bella.batch.tables.Instance;
import com.ke.bella.batch.tables.Queue;
import com.ke.bella.batch.tables.QueueHead;
import com.ke.bella.batch.tables.QueueMetadata;
import com.ke.bella.batch.tables.QueueSharding;
import com.ke.bella.batch.tables.TraceTaskShardingMapping;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>batch</code>.
     */
    public final Batch BATCH = Batch.BATCH;

    /**
     * The table <code>instance</code>.
     */
    public final Instance INSTANCE = Instance.INSTANCE;

    /**
     * The table <code>queue</code>.
     */
    public final Queue QUEUE = Queue.QUEUE;

    /**
     * The table <code>queue_head</code>.
     */
    public final QueueHead QUEUE_HEAD = QueueHead.QUEUE_HEAD;

    /**
     * The table <code>queue_metadata</code>.
     */
    public final QueueMetadata QUEUE_METADATA = QueueMetadata.QUEUE_METADATA;

    /**
     * The table <code>queue_sharding</code>.
     */
    public final QueueSharding QUEUE_SHARDING = QueueSharding.QUEUE_SHARDING;

    /**
     * The table <code>trace_task_sharding_mapping</code>.
     */
    public final TraceTaskShardingMapping TRACE_TASK_SHARDING_MAPPING = TraceTaskShardingMapping.TRACE_TASK_SHARDING_MAPPING;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Batch.BATCH,
            Instance.INSTANCE,
            Queue.QUEUE,
            QueueHead.QUEUE_HEAD,
            QueueMetadata.QUEUE_METADATA,
            QueueSharding.QUEUE_SHARDING,
            TraceTaskShardingMapping.TRACE_TASK_SHARDING_MAPPING
        );
    }
}
