/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch;


import com.ke.bella.batch.tables.Batch;
import com.ke.bella.batch.tables.Instance;
import com.ke.bella.batch.tables.Queue;
import com.ke.bella.batch.tables.QueueHead;
import com.ke.bella.batch.tables.QueueSharding;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index QUEUE_IDX_BATCH_ID = Internal.createIndex(DSL.name("idx_batch_id"), Queue.QUEUE, new OrderField[] { Queue.QUEUE.QUEUE_ }, false);
    public static final Index BATCH_IDX_ENDPOINT_CUID = Internal.createIndex(DSL.name("idx_endpoint_cuid"), Batch.BATCH, new OrderField[] { Batch.BATCH.ENDPOINT, Batch.BATCH.CUID }, false);
    public static final Index INSTANCE_IDX_IP_PORT = Internal.createIndex(DSL.name("idx_ip_port"), Instance.INSTANCE, new OrderField[] { Instance.INSTANCE.IP, Instance.INSTANCE.PORT }, false);
    public static final Index QUEUE_SHARDING_IDX_KEY = Internal.createIndex(DSL.name("idx_key"), QueueSharding.QUEUE_SHARDING, new OrderField[] { QueueSharding.QUEUE_SHARDING.KEY }, false);
    public static final Index QUEUE_SHARDING_IDX_LAST_KEY = Internal.createIndex(DSL.name("idx_last_key"), QueueSharding.QUEUE_SHARDING, new OrderField[] { QueueSharding.QUEUE_SHARDING.LAST_KEY }, false);
    public static final Index QUEUE_HEAD_IDX_QUEUE = Internal.createIndex(DSL.name("idx_queue"), QueueHead.QUEUE_HEAD, new OrderField[] { QueueHead.QUEUE_HEAD.QUEUE }, false);
}
