/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch;


import com.ke.bella.batch.tables.Batch;
import com.ke.bella.batch.tables.Instance;
import com.ke.bella.batch.tables.Queue;
import com.ke.bella.batch.tables.QueueHead;
import com.ke.bella.batch.tables.QueueMetadata;
import com.ke.bella.batch.tables.QueueSharding;
import com.ke.bella.batch.tables.TraceTaskShardingMapping;
import com.ke.bella.batch.tables.records.BatchRecord;
import com.ke.bella.batch.tables.records.InstanceRecord;
import com.ke.bella.batch.tables.records.QueueHeadRecord;
import com.ke.bella.batch.tables.records.QueueMetadataRecord;
import com.ke.bella.batch.tables.records.QueueRecord;
import com.ke.bella.batch.tables.records.QueueShardingRecord;
import com.ke.bella.batch.tables.records.TraceTaskShardingMappingRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BatchRecord> KEY_BATCH_IDX_BATCH_ID = Internal.createUniqueKey(Batch.BATCH, DSL.name("KEY_batch_idx_batch_id"), new TableField[] { Batch.BATCH.BATCH_ID }, true);
    public static final UniqueKey<BatchRecord> KEY_BATCH_PRIMARY = Internal.createUniqueKey(Batch.BATCH, DSL.name("KEY_batch_PRIMARY"), new TableField[] { Batch.BATCH.ID }, true);
    public static final UniqueKey<InstanceRecord> KEY_INSTANCE_PRIMARY = Internal.createUniqueKey(Instance.INSTANCE, DSL.name("KEY_instance_PRIMARY"), new TableField[] { Instance.INSTANCE.ID }, true);
    public static final UniqueKey<QueueRecord> KEY_QUEUE_PRIMARY = Internal.createUniqueKey(Queue.QUEUE, DSL.name("KEY_queue_PRIMARY"), new TableField[] { Queue.QUEUE.ID }, true);
    public static final UniqueKey<QueueRecord> KEY_QUEUE_UK_TASK_ID = Internal.createUniqueKey(Queue.QUEUE, DSL.name("KEY_queue_uk_task_id"), new TableField[] { Queue.QUEUE.TASK_ID }, true);
    public static final UniqueKey<QueueHeadRecord> KEY_QUEUE_HEAD_PRIMARY = Internal.createUniqueKey(QueueHead.QUEUE_HEAD, DSL.name("KEY_queue_head_PRIMARY"), new TableField[] { QueueHead.QUEUE_HEAD.ID }, true);
    public static final UniqueKey<QueueHeadRecord> KEY_QUEUE_HEAD_UK_QUEUE_LEVEL = Internal.createUniqueKey(QueueHead.QUEUE_HEAD, DSL.name("KEY_queue_head_uk_queue_level"), new TableField[] { QueueHead.QUEUE_HEAD.QUEUE, QueueHead.QUEUE_HEAD.LEVEL }, true);
    public static final UniqueKey<QueueHeadRecord> KEY_QUEUE_HEAD_UK_SCANNED_KEY = Internal.createUniqueKey(QueueHead.QUEUE_HEAD, DSL.name("KEY_queue_head_uk_scanned_key"), new TableField[] { QueueHead.QUEUE_HEAD.LAST_SCANNED_SHARDING_KEY }, true);
    public static final UniqueKey<QueueHeadRecord> KEY_QUEUE_HEAD_UK_WROTE_KEY = Internal.createUniqueKey(QueueHead.QUEUE_HEAD, DSL.name("KEY_queue_head_uk_wrote_key"), new TableField[] { QueueHead.QUEUE_HEAD.LAST_WROTE_SHARDING_KEY }, true);
    public static final UniqueKey<QueueMetadataRecord> KEY_QUEUE_METADATA_PRIMARY = Internal.createUniqueKey(QueueMetadata.QUEUE_METADATA, DSL.name("KEY_queue_metadata_PRIMARY"), new TableField[] { QueueMetadata.QUEUE_METADATA.ID }, true);
    public static final UniqueKey<QueueMetadataRecord> KEY_QUEUE_METADATA_UK_QUEUE = Internal.createUniqueKey(QueueMetadata.QUEUE_METADATA, DSL.name("KEY_queue_metadata_uk_queue"), new TableField[] { QueueMetadata.QUEUE_METADATA.QUEUE }, true);
    public static final UniqueKey<QueueShardingRecord> KEY_QUEUE_SHARDING_PRIMARY = Internal.createUniqueKey(QueueSharding.QUEUE_SHARDING, DSL.name("KEY_queue_sharding_PRIMARY"), new TableField[] { QueueSharding.QUEUE_SHARDING.ID }, true);
    public static final UniqueKey<QueueShardingRecord> KEY_QUEUE_SHARDING_UK_QUEUE_TABLE_KEY = Internal.createUniqueKey(QueueSharding.QUEUE_SHARDING, DSL.name("KEY_queue_sharding_uk_queue_table_key"), new TableField[] { QueueSharding.QUEUE_SHARDING.QUEUE_TABLE, QueueSharding.QUEUE_SHARDING.KEY }, true);
    public static final UniqueKey<TraceTaskShardingMappingRecord> KEY_TRACE_TASK_SHARDING_MAPPING_PRIMARY = Internal.createUniqueKey(TraceTaskShardingMapping.TRACE_TASK_SHARDING_MAPPING, DSL.name("KEY_trace_task_sharding_mapping_PRIMARY"), new TableField[] { TraceTaskShardingMapping.TRACE_TASK_SHARDING_MAPPING.ID }, true);
    public static final UniqueKey<TraceTaskShardingMappingRecord> KEY_TRACE_TASK_SHARDING_MAPPING_UK_TRACEID_SHARDINGKEY = Internal.createUniqueKey(TraceTaskShardingMapping.TRACE_TASK_SHARDING_MAPPING, DSL.name("KEY_trace_task_sharding_mapping_uk_traceId_shardingKey"), new TableField[] { TraceTaskShardingMapping.TRACE_TASK_SHARDING_MAPPING.TRACE_ID, TraceTaskShardingMapping.TRACE_TASK_SHARDING_MAPPING.SHARDING_KEY }, true);
}
