/*
 * This file is generated by jOOQ.
 */
package com.ke.bella.batch;


import com.ke.bella.batch.tables.Batch;
import com.ke.bella.batch.tables.Instance;
import com.ke.bella.batch.tables.Queue;
import com.ke.bella.batch.tables.QueueHead;
import com.ke.bella.batch.tables.QueueMetadata;
import com.ke.bella.batch.tables.QueueSharding;
import com.ke.bella.batch.tables.TraceTaskShardingMapping;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>batch</code>.
     */
    public static final Batch BATCH = Batch.BATCH;

    /**
     * The table <code>instance</code>.
     */
    public static final Instance INSTANCE = Instance.INSTANCE;

    /**
     * The table <code>queue</code>.
     */
    public static final Queue QUEUE = Queue.QUEUE;

    /**
     * The table <code>queue_head</code>.
     */
    public static final QueueHead QUEUE_HEAD = QueueHead.QUEUE_HEAD;

    /**
     * The table <code>queue_metadata</code>.
     */
    public static final QueueMetadata QUEUE_METADATA = QueueMetadata.QUEUE_METADATA;

    /**
     * The table <code>queue_sharding</code>.
     */
    public static final QueueSharding QUEUE_SHARDING = QueueSharding.QUEUE_SHARDING;

    /**
     * The table <code>trace_task_sharding_mapping</code>.
     */
    public static final TraceTaskShardingMapping TRACE_TASK_SHARDING_MAPPING = TraceTaskShardingMapping.TRACE_TASK_SHARDING_MAPPING;
}
